# Generated by Django 6.0.2 on 2026-03-30 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_accountcategorycode_account_address1_line2_and_more'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('categoryid', models.UUIDField(db_column='categoryid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('estimatedfuelconsumption', models.DecimalField(blank=True, db_column='estimatedfuelconsumption', decimal_places=2, max_digits=8, null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_equipment_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipmentcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('equipmentid', models.UUIDField(db_column='equipmentid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipmentnumber', models.CharField(db_column='equipmentnumber', max_length=20, unique=True)),
                ('ownershiptype', models.IntegerField(choices=[(0, 'Propio'), (1, 'Rentado de Tercero')], db_column='ownershiptype')),
                ('brand', models.CharField(db_column='brand', max_length=100)),
                ('model', models.CharField(db_column='model', max_length=100)),
                ('year', models.IntegerField(db_column='year')),
                ('serialnumber', models.CharField(db_column='serialnumber', max_length=100)),
                ('engineserialnumber', models.CharField(blank=True, db_column='engineserialnumber', max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, db_column='capacity', max_length=50, null=True)),
                ('currenthourmeter', models.DecimalField(db_column='currenthourmeter', decimal_places=2, default=0, max_digits=10)),
                ('operationalstatus', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Asignado a Proyecto'), (2, 'Rentado a Cliente'), (3, 'En Mantenimiento'), (4, 'Fuera de Servicio')], db_column='operationalstatus', default=0)),
                ('acquisitioncost', models.DecimalField(blank=True, db_column='acquisitioncost', decimal_places=2, max_digits=14, null=True)),
                ('purchasedate', models.DateField(blank=True, db_column='purchasedate', null=True)),
                ('estimatedusefullifehours', models.IntegerField(blank=True, db_column='estimatedusefullifehours', null=True)),
                ('salvagevalue', models.DecimalField(blank=True, db_column='salvagevalue', decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currentprojectid', models.ForeignKey(blank=True, db_column='currentprojectid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='projects.constructionproject')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_equipment', to=settings.AUTH_USER_MODEL)),
                ('supplierid', models.ForeignKey(blank=True, db_column='supplierid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_equipment', to='accounts.account')),
                ('categoryid', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='machinery.equipmentcategory')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInsurance',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('insuranceid', models.UUIDField(db_column='insuranceid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurancetype', models.IntegerField(choices=[(0, 'Daño Físico'), (1, 'Responsabilidad Civil'), (2, 'Transporte'), (3, 'Todo Riesgo')], db_column='insurancetype')),
                ('insurancecompany', models.CharField(db_column='insurancecompany', max_length=200)),
                ('policynumber', models.CharField(db_column='policynumber', max_length=50)),
                ('startdate', models.DateField(db_column='startdate')),
                ('expirydate', models.DateField(db_column='expirydate')),
                ('annualpremium', models.DecimalField(db_column='annualpremium', decimal_places=2, max_digits=12)),
                ('monthlypremium', models.DecimalField(db_column='monthlypremium', decimal_places=2, max_digits=12)),
                ('insuredamount', models.DecimalField(db_column='insuredamount', decimal_places=2, max_digits=14)),
                ('statecode', models.IntegerField(choices=[(0, 'Vigente'), (1, 'Vencida'), (2, 'Cancelada')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipmentid', models.ForeignKey(db_column='equipmentid', on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='machinery.equipment')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipmentinsurance',
                'ordering': ['-startdate'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentcategory',
            index=models.Index(fields=['statecode'], name='equipmentca_stateco_a49d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['categoryid', 'statecode'], name='equipment_categor_12c5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['operationalstatus'], name='equipment_operati_caada1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['ownershiptype'], name='equipment_ownersh_4cec52_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinsurance',
            index=models.Index(fields=['equipmentid', 'statecode'], name='equipmentin_equipme_93aa43_idx'),
        ),
    ]
