# Generated by Django 5.0.1 on 2026-03-31 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_accountcategorycode_account_address1_line2_and_more'),
        ('machinery', '0001_initial'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(db_column='brand', help_text='Denormalized from brandid for display', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(db_column='model', help_text='Denormalized from modelid for display', max_length=100),
        ),
        migrations.CreateModel(
            name='EquipmentBrand',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('brandid', models.UUIDField(db_column='brandid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('code', models.CharField(db_column='code', max_length=10, unique=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_equipment_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipmentbrand',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='brandid',
            field=models.ForeignKey(blank=True, db_column='brandid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='machinery.equipmentbrand'),
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('modelid', models.UUIDField(db_column='modelid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('brandid', models.ForeignKey(db_column='brandid', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='machinery.equipmentbrand')),
                ('categoryid', models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='machinery.equipmentcategory')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_equipment_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipmentmodel',
                'ordering': ['brandid', 'name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='modelid',
            field=models.ForeignKey(blank=True, db_column='modelid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='machinery.equipmentmodel'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['brandid'], name='equipment_brandid_0c7a02_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentbrand',
            index=models.Index(fields=['statecode'], name='equipmentbr_stateco_3a4c89_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['brandid', 'statecode'], name='equipmentmo_brandid_c59431_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('brandid', 'name'), name='unique_model_per_brand'),
        ),
    ]
