# Generated by Django 6.0.2 on 2026-04-03 01:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_add_brand_model_catalogs'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationReason',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('reasonid', models.UUIDField(db_column='reasonid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200, unique=True)),
                ('imputabilityvalue', models.IntegerField(db_column='imputabilityvalue', help_text='0=not imputable, 1=imputable')),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_justification_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'justificationreason',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('contractid', models.UUIDField(db_column='contractid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessorname', models.CharField(db_column='lessorname', help_text='Arrendador name', max_length=300)),
                ('economicnumber', models.CharField(db_column='economicnumber', help_text='No. Económico', max_length=50)),
                ('projectname', models.CharField(db_column='projectname', help_text='Obra name', max_length=300)),
                ('clientname', models.CharField(db_column='clientname', help_text='Client company name', max_length=300)),
                ('billingmodality', models.IntegerField(choices=[(0, 'Por Días'), (1, 'Por Horas')], db_column='billingmodality')),
                ('monthlyrate', models.DecimalField(db_column='monthlyrate', decimal_places=2, max_digits=14)),
                ('basemeasurement', models.IntegerField(db_column='basemeasurement', help_text='Base: 30 for days, 200 for hours')),
                ('taxrate', models.DecimalField(db_column='taxrate', decimal_places=4, default=Decimal('0.0800'), max_digits=5)),
                ('arrivalfreightstatus', models.CharField(blank=True, db_column='arrivalfreightstatus', max_length=50, null=True)),
                ('departurefreightstatus', models.CharField(blank=True, db_column='departurefreightstatus', max_length=50, null=True)),
                ('startdate', models.DateField(db_column='startdate')),
                ('enddate', models.DateField(blank=True, db_column='enddate', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('statuscode', models.IntegerField(choices=[(0, 'Activo'), (1, 'Completado'), (2, 'Cancelado')], db_column='statuscode', default=0)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipmentid', models.ForeignKey(db_column='equipmentid', on_delete=django.db.models.deletion.PROTECT, related_name='rentalcontracts', to='machinery.equipment')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_rental_contracts', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentalcontracts', to='projects.constructionproject')),
            ],
            options={
                'db_table': 'rentalcontract',
                'ordering': ['-startdate'],
            },
        ),
        migrations.CreateModel(
            name='DailyEquipmentLog',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('logid', models.UUIDField(db_column='logid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimationnumber', models.IntegerField(db_column='estimationnumber', help_text='No. Estimación')),
                ('logdate', models.DateField(db_column='logdate')),
                ('sequencenumber', models.IntegerField(db_column='sequencenumber', help_text='Folio correlativo')),
                ('hourmeterstart', models.DecimalField(db_column='hourmeterstart', decimal_places=2, max_digits=10)),
                ('hourmeterend', models.DecimalField(db_column='hourmeterend', decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True, db_column='comments', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('authorizedby', models.ForeignKey(blank=True, db_column='authorizedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_logs', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipmentid', models.ForeignKey(db_column='equipmentid', on_delete=django.db.models.deletion.PROTECT, related_name='dailylogs', to='machinery.equipment')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('justificationreasonid', models.ForeignKey(blank=True, db_column='justificationreasonid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailylogs', to='machinery.justificationreason')),
                ('contractid', models.ForeignKey(db_column='contractid', on_delete=django.db.models.deletion.PROTECT, related_name='dailylogs', to='machinery.rentalcontract')),
            ],
            options={
                'db_table': 'dailyequipmentlog',
                'ordering': ['logdate', 'sequencenumber'],
            },
        ),
        migrations.CreateModel(
            name='BillingEstimation',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('estimationid', models.UUIDField(db_column='estimationid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimationnumber', models.IntegerField(db_column='estimationnumber')),
                ('periodstart', models.DateField(db_column='periodstart')),
                ('periodend', models.DateField(db_column='periodend')),
                ('totalhours', models.DecimalField(db_column='totalhours', decimal_places=2, default=0, max_digits=10)),
                ('imputablehours', models.DecimalField(db_column='imputablehours', decimal_places=2, default=0, max_digits=10)),
                ('nonimputablehours', models.DecimalField(db_column='nonimputablehours', decimal_places=2, default=0, max_digits=10)),
                ('totaldays', models.IntegerField(db_column='totaldays', default=0)),
                ('imputabledays', models.IntegerField(db_column='imputabledays', default=0)),
                ('nonimputabledays', models.IntegerField(db_column='nonimputabledays', default=0)),
                ('sundaycount', models.IntegerField(db_column='sundaycount', default=0)),
                ('measurement', models.DecimalField(db_column='measurement', decimal_places=2, help_text='Imputable days or hours', max_digits=10)),
                ('unitprice', models.DecimalField(db_column='unitprice', decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, help_text='measurement x unitprice', max_digits=14)),
                ('advancepercentage', models.DecimalField(db_column='advancepercentage', decimal_places=4, max_digits=6)),
                ('accumulatedmeasurement', models.DecimalField(db_column='accumulatedmeasurement', decimal_places=2, max_digits=14)),
                ('accumulatedamount', models.DecimalField(db_column='accumulatedamount', decimal_places=2, max_digits=14)),
                ('taxamount', models.DecimalField(db_column='taxamount', decimal_places=2, max_digits=14)),
                ('totalamount', models.DecimalField(db_column='totalamount', decimal_places=2, max_digits=14)),
                ('conceptdescription', models.TextField(blank=True, db_column='conceptdescription', null=True)),
                ('observations', models.TextField(blank=True, db_column='observations', null=True)),
                ('statuscode', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Revisado'), (2, 'Aprobado'), (3, 'Facturado')], db_column='statuscode', default=0)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_billing_estimations', to=settings.AUTH_USER_MODEL)),
                ('contractid', models.ForeignKey(db_column='contractid', on_delete=django.db.models.deletion.PROTECT, related_name='estimations', to='machinery.rentalcontract')),
            ],
            options={
                'db_table': 'billingestimation',
                'ordering': ['contractid', 'estimationnumber'],
            },
        ),
        migrations.CreateModel(
            name='EstimationDeduction',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('deductionid', models.UUIDField(db_column='deductionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(db_column='concept', max_length=500)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, help_text='Negative value for deductions', max_digits=14)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('estimationid', models.ForeignKey(db_column='estimationid', on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='machinery.billingestimation')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estimationdeduction',
                'ordering': ['estimationid', 'concept'],
                'indexes': [models.Index(fields=['estimationid'], name='estimationd_estimat_7cab2a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='justificationreason',
            index=models.Index(fields=['statecode'], name='justificati_stateco_9482c4_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['equipmentid', 'statecode'], name='rentalcontr_equipme_2d8a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['statuscode'], name='rentalcontr_statusc_a0b9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentlog',
            index=models.Index(fields=['contractid', 'estimationnumber'], name='dailyequipm_contrac_36b670_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentlog',
            index=models.Index(fields=['equipmentid', 'logdate'], name='dailyequipm_equipme_9942eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyequipmentlog',
            index=models.Index(fields=['statecode'], name='dailyequipm_stateco_b87099_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyequipmentlog',
            constraint=models.UniqueConstraint(fields=('contractid', 'logdate'), name='unique_log_per_contract_per_day'),
        ),
        migrations.AddIndex(
            model_name='billingestimation',
            index=models.Index(fields=['contractid', 'estimationnumber'], name='billingesti_contrac_780d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingestimation',
            index=models.Index(fields=['statuscode'], name='billingesti_statusc_8b0fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingestimation',
            constraint=models.UniqueConstraint(fields=('contractid', 'estimationnumber'), name='unique_estimation_per_contract'),
        ),
    ]
