# Generated by Django 6.0.2 on 2026-02-19 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('incidentid', models.UUIDField(db_column='incidentid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('ticketnumber', models.CharField(db_column='ticketnumber', max_length=100, unique=True, verbose_name='Ticket Number')),
                ('casetypecode', models.IntegerField(blank=True, choices=[(1, 'Question'), (2, 'Problem'), (3, 'Request')], db_column='casetypecode', null=True, verbose_name='Case Type')),
                ('prioritycode', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], db_column='prioritycode', default=2, verbose_name='Priority')),
                ('caseorigincode', models.IntegerField(blank=True, choices=[(1, 'Phone'), (2, 'Email'), (3, 'Web'), (2483, 'Facebook'), (3986, 'Twitter'), (700610000, 'IoT')], db_column='caseorigincode', null=True, verbose_name='Origin')),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Resolved'), (2, 'Cancelled')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'In Progress'), (2, 'On Hold'), (3, 'Waiting for Details'), (4, 'Researching'), (5, 'Problem Solved'), (1000, 'Information Provided'), (6, 'Cancelled'), (2000, 'Merged')], db_column='statuscode', default=1)),
                ('firstresponsesent', models.BooleanField(db_column='firstresponsesent', default=False, verbose_name='First Response Sent')),
                ('resolutiontype', models.CharField(blank=True, db_column='resolutiontype', max_length=100, null=True, verbose_name='Resolution Type')),
                ('resolutionsummary', models.TextField(blank=True, db_column='resolutionsummary', null=True, verbose_name='Resolution Summary')),
                ('resolvedon', models.DateTimeField(blank=True, db_column='resolvedon', null=True, verbose_name='Resolved On')),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.account', verbose_name='Account')),
                ('contactid', models.ForeignKey(blank=True, db_column='contactid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='contacts.contact', verbose_name='Contact')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
                ('primarycontactid', models.ForeignKey(blank=True, db_column='primarycontactid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cases', to='contacts.contact', verbose_name='Primary Contact')),
                ('productid', models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'incident',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['statecode'], name='incident_stateco_3b67a9_idx'), models.Index(fields=['ownerid'], name='incident_ownerid_d5cea3_idx'), models.Index(fields=['accountid'], name='incident_account_91667c_idx'), models.Index(fields=['contactid'], name='incident_contact_d4c560_idx'), models.Index(fields=['statecode', 'ownerid'], name='incident_stateco_d105e1_idx'), models.Index(fields=['createdon'], name='incident_created_f4a7e9_idx')],
            },
        ),
    ]
