# Generated by Django 6.0.2 on 2026-03-01 23:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('opportunities', '0002_opportunity_accountid_opportunity_contactid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('projectid', models.UUIDField(db_column='projectid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectnumber', models.CharField(db_column='projectnumber', max_length=20, unique=True)),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'On Hold'), (3, 'Completed'), (4, 'Canceled')], db_column='statecode', default=0)),
                ('presentationdate', models.DateField(blank=True, db_column='presentationdate', null=True)),
                ('awarddate', models.DateField(blank=True, db_column='awarddate', null=True)),
                ('startdate', models.DateField(db_column='startdate')),
                ('contractenddate', models.DateField(db_column='contractenddate')),
                ('expectedenddate', models.DateField(blank=True, db_column='expectedenddate', null=True)),
                ('durationmonths', models.IntegerField(db_column='durationmonths', validators=[django.core.validators.MinValueValidator(1)])),
                ('projecttype', models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], db_column='projecttype')),
                ('biddingtype', models.IntegerField(choices=[(0, 'Open Bid'), (1, 'Invited Bid'), (2, 'Direct Award')], db_column='biddingtype')),
                ('contractamount_notax', models.DecimalField(db_column='contractamount_notax', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('contractamount_withtax', models.DecimalField(db_column='contractamount_withtax', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('advancepayment_notax', models.DecimalField(blank=True, db_column='advancepayment_notax', decimal_places=2, max_digits=19, null=True)),
                ('advancepayment_withtax', models.DecimalField(blank=True, db_column='advancepayment_withtax', decimal_places=2, max_digits=19, null=True)),
                ('exchangerate_mxn_usd', models.DecimalField(blank=True, db_column='exchangerate_mxn_usd', decimal_places=4, max_digits=12, null=True)),
                ('advancebond_amount', models.DecimalField(blank=True, db_column='advancebond_amount', decimal_places=2, max_digits=19, null=True)),
                ('advancebond_policycost', models.DecimalField(blank=True, db_column='advancebond_policycost', decimal_places=2, max_digits=19, null=True)),
                ('advancebond_validitystartdate', models.DateField(blank=True, db_column='advancebond_validitystartdate', null=True)),
                ('advancebond_validityenddate', models.DateField(blank=True, db_column='advancebond_validityenddate', null=True)),
                ('completionbond_amount', models.DecimalField(blank=True, db_column='completionbond_amount', decimal_places=2, max_digits=19, null=True)),
                ('completionbond_policycost', models.DecimalField(blank=True, db_column='completionbond_policycost', decimal_places=2, max_digits=19, null=True)),
                ('completionbond_validitystartdate', models.DateField(blank=True, db_column='completionbond_validitystartdate', null=True)),
                ('completionbond_validityenddate', models.DateField(blank=True, db_column='completionbond_validityenddate', null=True)),
                ('defectsbond_amount', models.DecimalField(blank=True, db_column='defectsbond_amount', decimal_places=2, max_digits=19, null=True)),
                ('defectsbond_policycost', models.DecimalField(blank=True, db_column='defectsbond_policycost', decimal_places=2, max_digits=19, null=True)),
                ('defectsbond_validitystartdate', models.DateField(blank=True, db_column='defectsbond_validitystartdate', null=True)),
                ('defectsbond_validityenddate', models.DateField(blank=True, db_column='defectsbond_validityenddate', null=True)),
                ('projectemail', models.EmailField(blank=True, db_column='projectemail', max_length=200, null=True)),
                ('emailconfigured', models.BooleanField(db_column='emailconfigured', default=False)),
                ('emailprotocol', models.IntegerField(blank=True, choices=[(0, 'IMAP'), (1, 'Graph API')], db_column='emailprotocol', null=True)),
                ('periodtype', models.IntegerField(choices=[(0, 'Weekly'), (1, 'Fortnightly')], db_column='periodtype', default=0)),
                ('alertthreshold_warning', models.DecimalField(blank=True, db_column='alertthreshold_warning', decimal_places=2, max_digits=5, null=True)),
                ('alertthreshold_critical', models.DecimalField(blank=True, db_column='alertthreshold_critical', decimal_places=2, max_digits=5, null=True)),
                ('alertthreshold_exceeded', models.DecimalField(blank=True, db_column='alertthreshold_exceeded', decimal_places=2, max_digits=5, null=True)),
                ('accountid', models.ForeignKey(db_column='accountid', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.account')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('opportunityid', models.ForeignKey(blank=True, db_column='opportunityid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='opportunities.opportunity')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Project',
                'verbose_name_plural': 'Construction Projects',
                'db_table': 'constructionproject',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSupplier',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('projectsupplierid', models.UUIDField(db_column='projectsupplierid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suppliernumber', models.IntegerField(db_column='suppliernumber')),
                ('rfc', models.CharField(db_column='rfc', max_length=13)),
                ('businessname', models.CharField(db_column='businessname', max_length=300)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('accountid', models.ForeignKey(db_column='accountid', on_delete=django.db.models.deletion.PROTECT, related_name='project_suppliers', to='accounts.account')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Supplier',
                'verbose_name_plural': 'Project Suppliers',
                'db_table': 'projectsupplier',
                'ordering': ['suppliernumber'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('teammemberid', models.UUIDField(db_column='teammemberid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('role', models.CharField(choices=[('ProjectManager', 'Project Manager'), ('AdminAssistant', 'Admin Assistant'), ('ProductionManager', 'Production Manager'), ('SiteEngineer', 'Site Engineer'), ('SafetyOfficer', 'Safety Officer'), ('QualityInspector', 'Quality Inspector'), ('ClientContact', 'Client Contact'), ('Other', 'Other')], db_column='role', max_length=50)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=200, null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Team Member',
                'verbose_name_plural': 'Project Team Members',
                'db_table': 'projectteammember',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectZone',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('zoneid', models.UUIDField(db_column='zoneid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('prefix', models.CharField(db_column='prefix', max_length=3)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('sortorder', models.IntegerField(db_column='sortorder', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Zone',
                'verbose_name_plural': 'Project Zones',
                'db_table': 'projectzone',
                'ordering': ['sortorder', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['name'], name='constructio_name_fb7caa_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['projectnumber'], name='constructio_project_8487d9_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['statecode', 'ownerid'], name='constructio_stateco_2804e0_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['accountid'], name='constructio_account_d1e71e_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['startdate'], name='constructio_startda_0218ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsupplier',
            constraint=models.UniqueConstraint(fields=('projectid', 'rfc'), name='unique_supplier_rfc_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectzone',
            constraint=models.UniqueConstraint(fields=('projectid', 'prefix'), name='unique_zone_prefix_per_project'),
        ),
    ]
