# Generated by Django 6.0.2 on 2026-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionproject',
            name='contractenddate',
            field=models.DateField(blank=True, db_column='contractenddate', null=True),
        ),
        migrations.AlterField(
            model_name='constructionproject',
            name='startdate',
            field=models.DateField(blank=True, db_column='startdate', null=True),
        ),
    ]
