# Generated by Django 5.0.1 on 2026-04-18 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_teammember_link_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsupplier',
            name='rfc',
            field=models.CharField(db_column='rfc', max_length=13, validators=[django.core.validators.RegexValidator(message='RFC must match SAT format (12-13 chars: letters + YYMMDD + 3 alphanum).', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')]),
        ),
    ]
