# Generated by Django 6.0.2 on 2026-05-18 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectsupplier_rfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='carinsurance_amount',
            field=models.DecimalField(blank=True, db_column='carinsurance_amount', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='carinsurance_policycost',
            field=models.DecimalField(blank=True, db_column='carinsurance_policycost', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='carinsurance_validityenddate',
            field=models.DateField(blank=True, db_column='carinsurance_validityenddate', null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='carinsurance_validitystartdate',
            field=models.DateField(blank=True, db_column='carinsurance_validitystartdate', null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='liabilityinsurance_amount',
            field=models.DecimalField(blank=True, db_column='liabilityinsurance_amount', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='liabilityinsurance_policycost',
            field=models.DecimalField(blank=True, db_column='liabilityinsurance_policycost', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='liabilityinsurance_validityenddate',
            field=models.DateField(blank=True, db_column='liabilityinsurance_validityenddate', null=True),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='liabilityinsurance_validitystartdate',
            field=models.DateField(blank=True, db_column='liabilityinsurance_validitystartdate', null=True),
        ),
        migrations.CreateModel(
            name='ProjectAssetUsage',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('assetusageid', models.UUIDField(db_column='assetusageid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, 'AC1 Equipo de cómputo y oficina'), (2, 'AC2 Maquinaria (Equipo Menor)'), (3, 'AC3 Maquinaria (Equipo Mayor)'), (4, 'AC4 Mobiliario campamentos'), (5, 'AC5 Mobiliario y equipamiento obra'), (6, 'AC6 Vehículos utilitarios')], db_column='category')),
                ('description', models.CharField(db_column='description', max_length=300)),
                ('plannedamount', models.DecimalField(db_column='plannedamount', decimal_places=2, default=0, max_digits=19)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='asset_usages', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Asset Usage',
                'verbose_name_plural': 'Project Asset Usages',
                'db_table': 'projectassetusage',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('riskid', models.UUIDField(db_column='riskid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('production_variance', models.DecimalField(db_column='production_variance', decimal_places=2, default=0, max_digits=19)),
                ('cost_variance', models.DecimalField(db_column='cost_variance', decimal_places=2, default=0, max_digits=19)),
                ('result_variance', models.DecimalField(db_column='result_variance', decimal_places=2, default=0, max_digits=19)),
                ('statuscode', models.IntegerField(choices=[(0, 'Open'), (1, 'Mitigated'), (2, 'Materialized'), (3, 'Closed')], db_column='statuscode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Risk',
                'verbose_name_plural': 'Project Risks',
                'db_table': 'projectrisk',
                'ordering': ['-createdon'],
            },
        ),
    ]
