# Generated by Django 5.0.1 on 2025-11-29 20:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('opportunities', '0002_opportunity_accountid_opportunity_contactid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('quoteid', models.UUIDField(db_column='quoteid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='Quote name/title', max_length=300)),
                ('quotenumber', models.CharField(db_column='quotenumber', help_text='Auto-generated quote number (e.g., Q-2024-001)', max_length=100, unique=True)),
                ('totalamount', models.DecimalField(db_column='totalamount', decimal_places=2, default=Decimal('0.00'), help_text='Total amount (calculated from line items)', max_digits=19)),
                ('totaldiscountamount', models.DecimalField(db_column='totaldiscountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totaltax', models.DecimalField(db_column='totaltax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totallineitemamount', models.DecimalField(db_column='totallineitemamount', decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items before discounts/taxes', max_digits=19)),
                ('discountpercentage', models.DecimalField(db_column='discountpercentage', decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('effectivefrom', models.DateField(blank=True, db_column='effectivefrom', help_text='Quote valid from date', null=True)),
                ('effectiveto', models.DateField(blank=True, db_column='effectiveto', help_text='Quote expiration date', null=True)),
                ('closedon', models.DateTimeField(blank=True, db_column='closedon', help_text='Date when quote was won/lost/canceled', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Won'), (3, 'Closed')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'In Progress'), (2, 'In Review'), (3, 'Won'), (4, 'Lost'), (5, 'Canceled'), (6, 'Revised')], db_column='statuscode', default=1)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='accounts.account')),
                ('contactid', models.ForeignKey(blank=True, db_column='contactid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='contacts.contact')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('opportunityid', models.ForeignKey(blank=True, db_column='opportunityid', help_text='Opportunity this quote is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='opportunities.opportunity')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quote',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('quotedetailid', models.UUIDField(db_column='quotedetailid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productname', help_text='Product or service name', max_length=100)),
                ('productdescription', models.TextField(blank=True, db_column='productdescription', null=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('priceperunit', models.DecimalField(db_column='priceperunit', decimal_places=2, help_text='Unit price', max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('manualdiscountamount', models.DecimalField(db_column='manualdiscountamount', decimal_places=2, default=Decimal('0.00'), help_text='Discount amount for this line', max_digits=19)),
                ('tax', models.DecimalField(db_column='tax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('baseamount', models.DecimalField(db_column='baseamount', decimal_places=2, help_text='quantity * priceperunit (auto-calculated)', max_digits=19)),
                ('extendedamount', models.DecimalField(db_column='extendedamount', decimal_places=2, help_text='baseamount - manualdiscountamount + tax (auto-calculated)', max_digits=19)),
                ('sequencenumber', models.IntegerField(db_column='sequencenumber', default=1)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('quoteid', models.ForeignKey(db_column='quoteid', on_delete=django.db.models.deletion.CASCADE, related_name='quote_details', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Quote Detail',
                'verbose_name_plural': 'Quote Details',
                'db_table': 'quotedetail',
                'ordering': ['quoteid', 'sequencenumber'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['statecode', 'ownerid'], name='quote_stateco_57de3e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['opportunityid'], name='quote_opportu_badd07_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['accountid'], name='quote_account_89a6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quotenumber'], name='quote_quotenu_e60b2c_idx'),
        ),
    ]
