# Generated by Django 6.0.2 on 2026-02-19 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('quotetemplateid', models.UUIDField(db_column='quotetemplateid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('category', models.CharField(blank=True, choices=[('standard', 'Standard'), ('custom', 'Custom'), ('industry', 'Industry'), ('service', 'Service'), ('product', 'Product'), ('bundle', 'Bundle')], db_column='category', max_length=20, null=True)),
                ('templatedata', models.JSONField(db_column='templatedata', default=dict, help_text='JSON with quote fields and line items')),
                ('isshared', models.BooleanField(db_column='isshared', default=False)),
                ('usagecount', models.IntegerField(db_column='usagecount', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_quote_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Template',
                'verbose_name_plural': 'Quote Templates',
                'db_table': 'quotetemplate',
                'ordering': ['-createdon'],
            },
        ),
    ]
