# Generated by Django 5.0.1 on 2026-03-05 00:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('expenses', '0004_alter_projectexpense_classificationstatus'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxSyncLog',
            fields=[
                ('synclogid', models.UUIDField(db_column='synclogid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('syncstatus', models.IntegerField(choices=[(0, 'Success'), (1, 'Partial'), (2, 'Failed')], db_column='syncstatus')),
                ('triggeredby', models.IntegerField(choices=[(0, 'Manual'), (1, 'Management Command')], db_column='triggeredby')),
                ('totalemailsfetched', models.IntegerField(db_column='totalemailsfetched', default=0)),
                ('newxmlattachments', models.IntegerField(db_column='newxmlattachments', default=0)),
                ('newpdfattachments', models.IntegerField(db_column='newpdfattachments', default=0)),
                ('duplicatesskipped', models.IntegerField(db_column='duplicatesskipped', default=0)),
                ('errorscount', models.IntegerField(db_column='errorscount', default=0)),
                ('errorsdetail', models.JSONField(db_column='errorsdetail', default=list)),
                ('startedon', models.DateTimeField(auto_now_add=True, db_column='startedon')),
                ('completedon', models.DateTimeField(blank=True, db_column='completedon', null=True)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='projects.constructionproject')),
                ('triggeredbyuserid', models.ForeignKey(blank=True, db_column='triggeredbyuserid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inboxsynclog',
                'ordering': ['-startedon'],
            },
        ),
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('incominginvoiceid', models.UUIDField(db_column='incominginvoiceid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'Classified'), (2, 'Linked'), (3, 'Rejected')], db_column='statecode', default=0)),
                ('emailmessageid', models.CharField(blank=True, db_column='emailmessageid', help_text='Internet Message-ID header for dedup', max_length=500, null=True)),
                ('emailsubject', models.CharField(blank=True, db_column='emailsubject', max_length=500, null=True)),
                ('emailfrom', models.CharField(blank=True, db_column='emailfrom', max_length=300, null=True)),
                ('emailreceivedon', models.DateTimeField(blank=True, db_column='emailreceivedon', null=True)),
                ('graphmessageid', models.CharField(blank=True, db_column='graphmessageid', help_text='Graph API message ID for attachment retrieval', max_length=500, null=True)),
                ('cfdiversion', models.CharField(blank=True, db_column='cfdiversion', max_length=10, null=True)),
                ('uuid', models.CharField(blank=True, db_column='uuid', help_text='TimbreFiscalDigital UUID — unique fiscal identifier', max_length=36, null=True)),
                ('serie', models.CharField(blank=True, db_column='serie', max_length=50, null=True)),
                ('folio', models.CharField(blank=True, db_column='folio', max_length=50, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='fecha', null=True)),
                ('fechatimbrado', models.DateTimeField(blank=True, db_column='fechatimbrado', null=True)),
                ('emisorrfc', models.CharField(blank=True, db_column='emisorrfc', max_length=13, null=True)),
                ('emisornombre', models.CharField(blank=True, db_column='emisornombre', max_length=300, null=True)),
                ('emisorregimenfiscal', models.CharField(blank=True, db_column='emisorregimenfiscal', max_length=10, null=True)),
                ('receptorrfc', models.CharField(blank=True, db_column='receptorrfc', max_length=13, null=True)),
                ('receptornombre', models.CharField(blank=True, db_column='receptornombre', max_length=300, null=True)),
                ('receptorusocfdi', models.CharField(blank=True, db_column='receptorusocfdi', max_length=10, null=True)),
                ('moneda', models.CharField(db_column='moneda', default='MXN', max_length=5)),
                ('tipocambio', models.DecimalField(db_column='tipocambio', decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totalimpuestostrasladados', models.DecimalField(db_column='totalimpuestostrasladados', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totalimpuestosretenidos', models.DecimalField(db_column='totalimpuestosretenidos', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('formapago', models.CharField(blank=True, db_column='formapago', max_length=5, null=True)),
                ('metodopago', models.CharField(blank=True, db_column='metodopago', max_length=5, null=True)),
                ('conceptosjson', models.JSONField(db_column='conceptosjson', default=list, help_text='Parsed CFDI line items as JSON array')),
                ('xmlfile', models.FileField(blank=True, db_column='xmlfile', null=True, upload_to='invoiceinbox/xml/%Y/%m/')),
                ('xmlfilename', models.CharField(blank=True, db_column='xmlfilename', max_length=255, null=True)),
                ('xmlfilesize', models.IntegerField(db_column='xmlfilesize', default=0)),
                ('pdffile', models.FileField(blank=True, db_column='pdffile', null=True, upload_to='invoiceinbox/pdf/%Y/%m/')),
                ('pdffilename', models.CharField(blank=True, db_column='pdffilename', max_length=255, null=True)),
                ('pdffilesize', models.IntegerField(db_column='pdffilesize', default=0)),
                ('matchtype', models.CharField(blank=True, db_column='matchtype', help_text='auto_uuid_match, auto_rfc_match, manual', max_length=50, null=True)),
                ('matchconfidence', models.IntegerField(db_column='matchconfidence', default=0, help_text='0-100 confidence score')),
                ('parseerrors', models.TextField(blank=True, db_column='parseerrors', null=True)),
                ('rejectionnotes', models.TextField(blank=True, db_column='rejectionnotes', null=True)),
                ('classificationnotes', models.TextField(blank=True, db_column='classificationnotes', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('imputationcodeid', models.ForeignKey(blank=True, db_column='imputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoices', to='budgets.imputationcode')),
                ('linkedexpenseid', models.ForeignKey(blank=True, db_column='linkedexpenseid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoices', to='expenses.projectexpense')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoices', to='projects.constructionproject')),
                ('suggestedexpenseid', models.ForeignKey(blank=True, db_column='suggestedexpenseid', help_text='Auto-suggested expense match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expenses.projectexpense')),
            ],
            options={
                'db_table': 'incominginvoice',
                'ordering': ['-emailreceivedon'],
                'indexes': [models.Index(fields=['statecode'], name='incominginv_stateco_e909e3_idx'), models.Index(fields=['projectid', 'statecode'], name='incominginv_project_9c02bf_idx'), models.Index(fields=['uuid'], name='incominginv_uuid_c74f98_idx'), models.Index(fields=['emisorrfc'], name='incominginv_emisorr_ae4a84_idx'), models.Index(fields=['graphmessageid'], name='incominginv_graphme_0d572b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='incominginvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('uuid__isnull', False)), fields=('uuid',), name='unique_incoming_invoice_uuid'),
        ),
    ]
