# Generated by Django 6.0.2 on 2026-02-20 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.UUIDField(db_column='notificationid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typecode', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('quote', 'Quote'), ('task', 'Task'), ('mention', 'Mention'), ('system', 'System')], db_column='typecode', max_length=20)),
                ('prioritycode', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], db_column='prioritycode', default=1)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('isread', models.BooleanField(db_column='isread', default=False)),
                ('isarchived', models.BooleanField(db_column='isarchived', default=False)),
                ('readon', models.DateTimeField(blank=True, db_column='readon', null=True)),
                ('relatedentityid', models.UUIDField(blank=True, db_column='relatedentityid', null=True)),
                ('relatedentitytype', models.CharField(blank=True, db_column='relatedentitytype', max_length=50, null=True)),
                ('relatedentityname', models.CharField(blank=True, db_column='relatedentityname', max_length=255, null=True)),
                ('actionurl', models.CharField(blank=True, db_column='actionurl', max_length=500, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('actorid', models.ForeignKey(blank=True, db_column='actorid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['ownerid', 'isread'], name='notificatio_ownerid_edebd8_idx'), models.Index(fields=['ownerid', 'isarchived'], name='notificatio_ownerid_c75b17_idx'), models.Index(fields=['ownerid', 'typecode'], name='notificatio_ownerid_041945_idx'), models.Index(fields=['createdon'], name='notificatio_created_f9c868_idx')],
            },
        ),
    ]
