# Generated by Django 5.0.1 on 2025-11-28 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRole',
            fields=[
                ('securityroleid', models.UUIDField(db_column='securityroleid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'verbose_name': 'Security Role',
                'verbose_name_plural': 'Security Roles',
                'db_table': 'securityrole',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('systemuserid', models.UUIDField(db_column='systemuserid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emailaddress1', models.EmailField(db_column='emailaddress1', max_length=100, unique=True)),
                ('fullname', models.CharField(db_column='fullname', max_length=200)),
                ('isdisabled', models.BooleanField(db_column='isdisabled', default=False)),
                ('failedloginattempts', models.IntegerField(db_column='failedloginattempts', default=0)),
                ('lastlogindate', models.DateTimeField(blank=True, db_column='lastlogindate', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('securityroleid', models.ForeignKey(db_column='securityroleid', on_delete=django.db.models.deletion.PROTECT, to='users.securityrole')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'systemuser',
                'ordering': ['fullname'],
                'indexes': [models.Index(fields=['isdisabled', 'securityroleid'], name='systemuser_isdisab_b047c7_idx')],
            },
        ),
    ]
