# Generated by Django 6.0.2 on 2026-03-27 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('agentrunid', models.UUIDField(db_column='agentrunid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agenttype', models.IntegerField(choices=[(1, 'Lead Scoring'), (2, 'Duplicate Detection'), (3, 'Expense Classification'), (4, 'Budget Alert'), (5, 'Pipeline Forecast'), (6, 'Next Best Action'), (7, 'Quote Optimization'), (8, 'Opportunity Stage Advisor'), (9, 'Lead Qualification Assistant'), (10, 'Cost Variance Analyzer'), (11, 'Provision Reconciliation'), (12, 'Client Estimate Generator'), (13, 'Payroll Validation'), (14, 'Attendance Anomaly'), (15, 'Project Staffing'), (16, 'Invoice Collection'), (17, 'Corporate Allocation Optimizer'), (18, 'Cash Flow Projector'), (19, 'Activity Summarizer'), (20, 'Email-to-CRM Linker'), (21, 'Meeting Prep'), (22, 'Data Quality'), (23, 'Audit Compliance'), (24, 'Permission Anomaly'), (25, 'Proyección Cost Estimator'), (26, 'Bid Analysis'), (27, 'Smart Notification Router'), (28, 'Escalation'), (29, 'Invoice Inbox Processor')], db_column='agenttype')),
                ('statecode', models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Completed'), (3, 'Failed'), (4, 'Cancelled')], db_column='statecode', default=0)),
                ('input_params', models.JSONField(db_column='inputparams', default=dict)),
                ('output_summary', models.JSONField(db_column='outputsummary', default=dict)),
                ('suggestions_count', models.IntegerField(db_column='suggestionscount', default=0)),
                ('accepted_count', models.IntegerField(db_column='acceptedcount', default=0)),
                ('rejected_count', models.IntegerField(db_column='rejectedcount', default=0)),
                ('duration_ms', models.IntegerField(blank=True, db_column='durationms', null=True)),
                ('error_message', models.TextField(blank=True, db_column='errormessage', default='')),
                ('triggered_by', models.CharField(db_column='triggeredby', default='manual', help_text='manual | schedule | event', max_length=20)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agentrun',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='AgentSuggestion',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('suggestionid', models.UUIDField(db_column='suggestionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agenttype', models.IntegerField(choices=[(1, 'Lead Scoring'), (2, 'Duplicate Detection'), (3, 'Expense Classification'), (4, 'Budget Alert'), (5, 'Pipeline Forecast'), (6, 'Next Best Action'), (7, 'Quote Optimization'), (8, 'Opportunity Stage Advisor'), (9, 'Lead Qualification Assistant'), (10, 'Cost Variance Analyzer'), (11, 'Provision Reconciliation'), (12, 'Client Estimate Generator'), (13, 'Payroll Validation'), (14, 'Attendance Anomaly'), (15, 'Project Staffing'), (16, 'Invoice Collection'), (17, 'Corporate Allocation Optimizer'), (18, 'Cash Flow Projector'), (19, 'Activity Summarizer'), (20, 'Email-to-CRM Linker'), (21, 'Meeting Prep'), (22, 'Data Quality'), (23, 'Audit Compliance'), (24, 'Permission Anomaly'), (25, 'Proyección Cost Estimator'), (26, 'Bid Analysis'), (27, 'Smart Notification Router'), (28, 'Escalation'), (29, 'Invoice Inbox Processor')], db_column='agenttype')),
                ('statecode', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Expired')], db_column='statecode', default=0)),
                ('relatedentityid', models.UUIDField(blank=True, db_column='relatedentityid', null=True)),
                ('relatedentitytype', models.CharField(blank=True, db_column='relatedentitytype', default='', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('confidence', models.FloatField(db_column='confidence', default=0.0, help_text='Confidence score 0.0 - 1.0')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('exceeded', 'Exceeded')], db_column='severity', default='info', max_length=20)),
                ('suggested_action', models.CharField(blank=True, db_column='suggestedaction', default='', max_length=100)),
                ('suggested_data', models.JSONField(db_column='suggesteddata', default=dict)),
                ('resolved_on', models.DateTimeField(blank=True, db_column='resolvedon', null=True)),
                ('resolution_notes', models.TextField(blank=True, db_column='resolutionnotes', default='')),
                ('agentrun', models.ForeignKey(db_column='agentrunid', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='agents.agentrun')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolvedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agentsuggestion',
                'ordering': ['-confidence', '-createdon'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('agentconfigid', models.UUIDField(db_column='agentconfigid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agenttype', models.IntegerField(choices=[(1, 'Lead Scoring'), (2, 'Duplicate Detection'), (3, 'Expense Classification'), (4, 'Budget Alert'), (5, 'Pipeline Forecast'), (6, 'Next Best Action'), (7, 'Quote Optimization'), (8, 'Opportunity Stage Advisor'), (9, 'Lead Qualification Assistant'), (10, 'Cost Variance Analyzer'), (11, 'Provision Reconciliation'), (12, 'Client Estimate Generator'), (13, 'Payroll Validation'), (14, 'Attendance Anomaly'), (15, 'Project Staffing'), (16, 'Invoice Collection'), (17, 'Corporate Allocation Optimizer'), (18, 'Cash Flow Projector'), (19, 'Activity Summarizer'), (20, 'Email-to-CRM Linker'), (21, 'Meeting Prep'), (22, 'Data Quality'), (23, 'Audit Compliance'), (24, 'Permission Anomaly'), (25, 'Proyección Cost Estimator'), (26, 'Bid Analysis'), (27, 'Smart Notification Router'), (28, 'Escalation'), (29, 'Invoice Inbox Processor')], db_column='agenttype')),
                ('enabled', models.BooleanField(db_column='enabled', default=True)),
                ('config', models.JSONField(db_column='config', default=dict, help_text='Agent-specific configuration (thresholds, weights, rules)')),
                ('schedule_cron', models.CharField(blank=True, db_column='schedulecron', default='', help_text='Cron expression for scheduled runs. Empty = on-demand only.', max_length=50)),
                ('projectid', models.UUIDField(blank=True, db_column='projectid', help_text='Scope to a specific project (null = global)', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(blank=True, db_column='ownerid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agentconfig',
                'ordering': ['agenttype'],
                'unique_together': {('agenttype', 'projectid')},
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agenttype', '-createdon'], name='agentrun_agentty_eed3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['statecode'], name='agentrun_stateco_4decb6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['agenttype', 'statecode'], name='agentsugges_agentty_a92cce_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['relatedentitytype', 'relatedentityid'], name='agentsugges_related_5f0592_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['agentrun', '-confidence'], name='agentsugges_agentru_da4ca7_idx'),
        ),
    ]
