# Generated by Django 6.0.2 on 2026-03-01 23:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('attachmentid', models.UUIDField(db_column='attachmentid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('suggestedfilename', models.CharField(db_column='suggestedfilename', max_length=255)),
                ('filetype', models.IntegerField(choices=[(0, 'PDF'), (1, 'XML'), (2, 'Image'), (99, 'Other')], db_column='filetype')),
                ('filesize', models.IntegerField(db_column='filesize')),
                ('mimetype', models.CharField(db_column='mimetype', max_length=100)),
                ('storageurl', models.CharField(db_column='storageurl', max_length=500)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
            ],
            options={
                'db_table': 'expenseattachment',
            },
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('expenselineid', models.UUIDField(db_column='expenselineid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linenumber', models.IntegerField(db_column='linenumber')),
                ('description', models.CharField(db_column='description', max_length=500)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=4, max_digits=12)),
                ('unitprice', models.DecimalField(db_column='unitprice', decimal_places=4, max_digits=19)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('taxamount', models.DecimalField(db_column='taxamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('retentionamount', models.DecimalField(db_column='retentionamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('discountamount', models.DecimalField(db_column='discountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('netamount', models.DecimalField(db_column='netamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
            ],
            options={
                'db_table': 'expenseline',
                'ordering': ['linenumber'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('expenseid', models.UUIDField(db_column='expenseid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classificationstatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Classified'), (3, 'Partial')], db_column='classificationstatus', default=1)),
                ('documenttype', models.IntegerField(choices=[(0, 'Invoice'), (1, 'Credit Note'), (2, 'No Invoice Expense'), (3, 'Payroll'), (4, 'Provision')], db_column='documenttype')),
                ('supplierrfc', models.CharField(blank=True, db_column='supplierrfc', max_length=13, null=True)),
                ('suppliername', models.CharField(blank=True, db_column='suppliername', max_length=300, null=True)),
                ('invoiceuuid', models.CharField(blank=True, db_column='invoiceuuid', max_length=36, null=True)),
                ('invoicefolio', models.CharField(blank=True, db_column='invoicefolio', max_length=50, null=True)),
                ('invoicedate', models.DateField(blank=True, db_column='invoicedate', null=True)),
                ('expensesource', models.CharField(blank=True, db_column='expensesource', max_length=300, null=True)),
                ('payrolltype', models.IntegerField(blank=True, choices=[(0, 'Weekly'), (1, 'Biweekly')], db_column='payrolltype', null=True)),
                ('workername', models.CharField(blank=True, db_column='workername', max_length=200, null=True)),
                ('provisionstatus', models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Converted'), (2, 'Canceled')], db_column='provisionstatus', null=True)),
                ('paymentmethod', models.IntegerField(blank=True, choices=[(0, 'Credit Card'), (1, 'Bank Transfer'), (2, 'Cash'), (3, 'Check'), (4, 'Debit Card'), (99, 'Other')], db_column='paymentmethod', null=True)),
                ('paymentstatus', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Partially Paid'), (3, 'Overdue')], db_column='paymentstatus', default=0)),
                ('currency', models.IntegerField(choices=[(0, 'MXN'), (1, 'USD')], db_column='currency', default=0)),
                ('exchangerate', models.DecimalField(db_column='exchangerate', decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('taxamount', models.DecimalField(db_column='taxamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('retentionamount', models.DecimalField(db_column='retentionamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('discountamount', models.DecimalField(db_column='discountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('netamount', models.DecimalField(db_column='netamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('verificationstatus', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Discrepancy')], db_column='verificationstatus', default=0)),
                ('verificationnotes', models.TextField(blank=True, db_column='verificationnotes', null=True)),
                ('verifiedon', models.DateTimeField(blank=True, db_column='verifiedon', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Canceled')], db_column='statecode', default=0)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
            ],
            options={
                'db_table': 'projectexpense',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationLog',
            fields=[
                ('classificationlogid', models.UUIDField(db_column='classificationlogid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previousimputationcode', models.CharField(blank=True, db_column='previousimputationcode', max_length=20, null=True)),
                ('newimputationcode', models.CharField(blank=True, db_column='newimputationcode', max_length=20, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Assigned'), (1, 'Changed'), (2, 'Removed')], db_column='action')),
                ('classifiedbyname', models.CharField(db_column='classifiedbyname', max_length=200)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('classifiedby', models.ForeignKey(db_column='classifiedby', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newimputationcodeid', models.ForeignKey(blank=True, db_column='newimputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='budgets.imputationcode')),
                ('previousimputationcodeid', models.ForeignKey(blank=True, db_column='previousimputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='budgets.imputationcode')),
            ],
            options={
                'db_table': 'classificationlog',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='ClientEstimate',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('estimateid', models.UUIDField(db_column='estimateid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimatenumber', models.IntegerField(db_column='estimatenumber')),
                ('invoicenumber', models.CharField(blank=True, db_column='invoicenumber', max_length=50, null=True)),
                ('invoicedate', models.DateField(blank=True, db_column='invoicedate', null=True)),
                ('estimationperiod', models.CharField(blank=True, db_column='estimationperiod', max_length=50, null=True)),
                ('estimatetype', models.IntegerField(choices=[(0, 'Estimate'), (1, 'Other')], db_column='estimatetype', default=0)),
                ('estimatedamount', models.DecimalField(db_column='estimatedamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('advanceamortization', models.DecimalField(db_column='advanceamortization', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('otherdeductions', models.DecimalField(db_column='otherdeductions', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('materialdeductions', models.DecimalField(db_column='materialdeductions', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('guaranteefund', models.DecimalField(db_column='guaranteefund', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totaldeductions', models.DecimalField(db_column='totaldeductions', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('amountnotax', models.DecimalField(db_column='amountnotax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('taxamount', models.DecimalField(db_column='taxamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('taxretained', models.DecimalField(db_column='taxretained', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totalinvoiced', models.DecimalField(db_column='totalinvoiced', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('collectableamount', models.DecimalField(db_column='collectableamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('paymentstatus', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Partially Paid'), (3, 'Overdue')], db_column='paymentstatus', default=0)),
                ('paymentdate', models.DateField(blank=True, db_column='paymentdate', null=True)),
                ('amountpaid', models.DecimalField(db_column='amountpaid', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Paid'), (2, 'Canceled')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('periodid', models.ForeignKey(blank=True, db_column='periodid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='budgets.imputationperiod')),
            ],
            options={
                'db_table': 'clientestimate',
                'ordering': ['-createdon'],
            },
        ),
    ]
