# Generated by Django 6.0.2 on 2026-03-01 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('expenses', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientestimate',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.constructionproject'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='imputationcodeid',
            field=models.ForeignKey(blank=True, db_column='imputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budgets.imputationcode'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='ownerid',
            field=models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='periodid',
            field=models.ForeignKey(db_column='periodid', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.imputationperiod'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.constructionproject'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='provisionconvertedfromid',
            field=models.ForeignKey(blank=True, db_column='provisionconvertedfromid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_expenses', to='expenses.projectexpense'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='verifiedby',
            field=models.ForeignKey(blank=True, db_column='verifiedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='expenseid',
            field=models.ForeignKey(db_column='expenseid', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.projectexpense'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='expenseid',
            field=models.ForeignKey(db_column='expenseid', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.projectexpense'),
        ),
        migrations.AddField(
            model_name='classificationlog',
            name='expenseid',
            field=models.ForeignKey(db_column='expenseid', on_delete=django.db.models.deletion.CASCADE, related_name='classification_logs', to='expenses.projectexpense'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['projectid', 'statecode'], name='projectexpe_project_18416b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['projectid', 'classificationstatus'], name='projectexpe_project_d640f3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['projectid', 'periodid'], name='projectexpe_project_0d2afa_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('invoiceuuid__isnull', False)), fields=('projectid', 'invoiceuuid'), name='unique_invoice_per_project'),
        ),
    ]
