# Generated by Django 6.0.2 on 2026-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(blank=True, db_column='file', null=True, upload_to='expenses/attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='storageurl',
            field=models.CharField(blank=True, db_column='storageurl', default='', max_length=500),
        ),
    ]
