# Generated by Django 6.0.2 on 2026-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_file_field_to_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='classificationstatus',
            field=models.IntegerField(choices=[(1, 'Unclassified'), (2, 'Classified'), (3, 'Partial')], db_column='classificationstatus', default=1),
        ),
    ]
