# Generated by Django 6.0.2 on 2026-03-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('expenses', '0004_alter_projectexpense_classificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseline',
            name='imputationcodeid',
            field=models.ForeignKey(blank=True, db_column='imputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_lines', to='budgets.imputationcode'),
        ),
    ]
