# Generated by Django 6.0.2 on 2026-03-29 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('corporate', '0002_alter_corporatebudget_unique_together_and_more'),
        ('expenses', '0005_add_imputationcodeid_to_expenseline'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='corporatebudgetid',
            field=models.ForeignKey(blank=True, db_column='corporatebudgetid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_expenses', to='corporate.corporatebudget'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='corporatecategory',
            field=models.CharField(blank=True, db_column='corporatecategory', help_text='Corporate expense category (4.1-4.9)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='expensescope',
            field=models.IntegerField(choices=[(0, 'Project'), (1, 'Corporate')], db_column='expensescope', default=0),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='periodid',
            field=models.ForeignKey(blank=True, db_column='periodid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.imputationperiod'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='projectid',
            field=models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.constructionproject'),
        ),
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['expensescope', 'corporatebudgetid', 'corporatecategory'], name='idx_corporate_expense_scope'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('expensescope', 1), ('invoiceuuid__isnull', False)), fields=('corporatebudgetid', 'invoiceuuid'), name='unique_invoice_per_budget'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expensescope', 0), ('projectid__isnull', False)), models.Q(('corporatebudgetid__isnull', False), ('corporatecategory__isnull', False), ('expensescope', 1)), _connector='OR'), name='expense_scope_integrity'),
        ),
    ]
