# Generated by Django 6.0.2 on 2026-04-05 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_add_accounting_fields_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientestimate',
            name='advancepayment',
            field=models.DecimalField(db_column='advancepayment', decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='clientestimate',
            name='estimatetype',
            field=models.IntegerField(choices=[(0, 'Estimate'), (1, 'Advance'), (2, 'Advance Amortization')], db_column='estimatetype', default=0),
        ),
    ]
