# Generated by Django 5.0.1 on 2026-04-18 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_imputationcodebudget_unique_code_period_budget_and_more'),
        ('corporate', '0002_alter_corporatebudget_unique_together_and_more'),
        ('expenses', '0008_add_advancepayment_and_estimate_types'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectexpense',
            index=models.Index(fields=['projectid', '-createdon'], name='idx_expense_project_createdon'),
        ),
    ]
