# Generated by Django 5.0.1 on 2026-03-21 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('projects', '0003_teammember_link_systemuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateBudget',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('corporatebudgetid', models.UUIDField(db_column='corporatebudgetid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscalyear', models.IntegerField(db_column='fiscalyear')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('currency', models.CharField(db_column='currency', default='MXN', max_length=3)),
                ('totalbudget', models.DecimalField(db_column='totalbudget', decimal_places=2, default=0, max_digits=19)),
                ('monthlypromedio', models.DecimalField(db_column='monthlypromedio', decimal_places=2, default=0, max_digits=19)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved'), (2, 'Closed')], db_column='statecode', default=0)),
                ('approveddate', models.DateField(blank=True, db_column='approveddate', null=True)),
                ('approvedby', models.ForeignKey(blank=True, db_column='approvedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corporate_budgets', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_corporate_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporatebudget',
                'ordering': ['-fiscalyear'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAllocation',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('allocationid', models.UUIDField(db_column='allocationid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('prorationmethod', models.IntegerField(choices=[(0, 'By Direct Cost %'), (1, 'By Contract Amount %'), (2, 'By Duration %'), (3, 'Manual %'), (4, 'Hybrid')], db_column='prorationmethod')),
                ('totalamountallocated', models.DecimalField(db_column='totalamountallocated', decimal_places=2, default=0, max_digits=19)),
                ('unallocatedamount', models.DecimalField(db_column='unallocatedamount', decimal_places=2, default=0, max_digits=19)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'Applied'), (2, 'Reversed')], db_column='statecode', default=0)),
                ('appliedon', models.DateTimeField(blank=True, db_column='appliedon', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('corporatebudgetid', models.ForeignKey(db_column='corporatebudgetid', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='corporate.corporatebudget')),
            ],
            options={
                'db_table': 'corporateallocation',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='CorporateBudgetVersion',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('versionid', models.UUIDField(db_column='versionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versionnumber', models.IntegerField(db_column='versionnumber')),
                ('label', models.CharField(db_column='label', max_length=100)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('approveddate', models.DateField(blank=True, db_column='approveddate', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Superseded')], db_column='statecode', default=0)),
                ('corporatebudgetid', models.ForeignKey(db_column='corporatebudgetid', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='corporate.corporatebudget')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporatebudgetversion',
                'ordering': ['-versionnumber'],
            },
        ),
        migrations.CreateModel(
            name='CorporateBudgetLine',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('budgetlineid', models.UUIDField(db_column='budgetlineid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorycode', models.CharField(choices=[('4.1', 'Personal Directivo y Administrativo'), ('4.2', 'Infraestructura de Oficina'), ('4.3', 'Equipamiento y Tecnología'), ('4.4', 'Vehículos y Transporte'), ('4.5', 'Seguros y Obligaciones'), ('4.6', 'Desarrollo Comercial y Licitaciones'), ('4.7', 'Capacitación y Desarrollo'), ('4.8', 'Gastos Financieros'), ('4.9', 'Varios / No Clasificados')], db_column='categorycode', max_length=5)),
                ('categoryname', models.CharField(db_column='categoryname', max_length=200)),
                ('jan', models.DecimalField(db_column='jan', decimal_places=2, default=0, max_digits=19)),
                ('feb', models.DecimalField(db_column='feb', decimal_places=2, default=0, max_digits=19)),
                ('mar', models.DecimalField(db_column='mar', decimal_places=2, default=0, max_digits=19)),
                ('apr', models.DecimalField(db_column='apr', decimal_places=2, default=0, max_digits=19)),
                ('may', models.DecimalField(db_column='may', decimal_places=2, default=0, max_digits=19)),
                ('jun', models.DecimalField(db_column='jun', decimal_places=2, default=0, max_digits=19)),
                ('jul', models.DecimalField(db_column='jul', decimal_places=2, default=0, max_digits=19)),
                ('aug', models.DecimalField(db_column='aug', decimal_places=2, default=0, max_digits=19)),
                ('sep', models.DecimalField(db_column='sep', decimal_places=2, default=0, max_digits=19)),
                ('oct', models.DecimalField(db_column='oct', decimal_places=2, default=0, max_digits=19)),
                ('nov', models.DecimalField(db_column='nov', decimal_places=2, default=0, max_digits=19)),
                ('dec', models.DecimalField(db_column='dec', decimal_places=2, default=0, max_digits=19)),
                ('annualamount', models.DecimalField(db_column='annualamount', decimal_places=2, default=0, max_digits=19)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('versionid', models.ForeignKey(db_column='versionid', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='corporate.corporatebudgetversion')),
            ],
            options={
                'db_table': 'corporatebudgetline',
                'ordering': ['categorycode'],
            },
        ),
        migrations.CreateModel(
            name='CorporateExpense',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('corporateexpenseid', models.UUIDField(db_column='corporateexpenseid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorycode', models.CharField(choices=[('4.1', 'Personal Directivo y Administrativo'), ('4.2', 'Infraestructura de Oficina'), ('4.3', 'Equipamiento y Tecnología'), ('4.4', 'Vehículos y Transporte'), ('4.5', 'Seguros y Obligaciones'), ('4.6', 'Desarrollo Comercial y Licitaciones'), ('4.7', 'Capacitación y Desarrollo'), ('4.8', 'Gastos Financieros'), ('4.9', 'Varios / No Clasificados')], db_column='categorycode', max_length=5)),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('budgetedamount', models.DecimalField(db_column='budgetedamount', decimal_places=2, default=0, max_digits=19)),
                ('actualamount', models.DecimalField(db_column='actualamount', decimal_places=2, default=0, max_digits=19)),
                ('variance', models.DecimalField(db_column='variance', decimal_places=2, default=0, max_digits=19)),
                ('variancepercent', models.DecimalField(db_column='variancepercent', decimal_places=2, default=0, max_digits=7)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('statecode', models.IntegerField(db_column='statecode', default=0)),
                ('corporatebudgetid', models.ForeignKey(db_column='corporatebudgetid', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='corporate.corporatebudget')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporateexpense',
                'ordering': ['year', 'month', 'categorycode'],
            },
        ),
        migrations.CreateModel(
            name='WhatIfSimulation',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('simulationid', models.UUIDField(db_column='simulationid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('fiscalyear', models.IntegerField(db_column='fiscalyear')),
                ('parameters', models.JSONField(db_column='parameters', default=dict)),
                ('results', models.JSONField(db_column='results', default=dict)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Archived')], db_column='statecode', default=0)),
                ('corporatebudgetid', models.ForeignKey(blank=True, db_column='corporatebudgetid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='corporate.corporatebudget')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatifsimulation',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAllocationLine',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('allocationlineid', models.UUIDField(db_column='allocationlineid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prorationmethod', models.IntegerField(choices=[(0, 'By Direct Cost %'), (1, 'By Contract Amount %'), (2, 'By Duration %'), (3, 'Manual %'), (4, 'Hybrid')], db_column='prorationmethod')),
                ('weightvalue', models.DecimalField(db_column='weightvalue', decimal_places=4, default=0, max_digits=19)),
                ('weightpercent', models.DecimalField(db_column='weightpercent', decimal_places=4, default=0, max_digits=7)),
                ('allocatedamount', models.DecimalField(db_column='allocatedamount', decimal_places=2, default=0, max_digits=19)),
                ('allocationid', models.ForeignKey(db_column='allocationid', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='corporate.corporateallocation')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('imputationcodeid', models.ForeignKey(blank=True, db_column='imputationcodeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_allocation_lines', to='budgets.imputationcode')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.PROTECT, related_name='corporate_allocations', to='projects.constructionproject')),
            ],
            options={
                'db_table': 'corporateallocationline',
                'ordering': ['-allocatedamount'],
                'indexes': [models.Index(fields=['projectid'], name='corporateal_project_2bf33d_idx')],
                'unique_together': {('allocationid', 'projectid')},
            },
        ),
        migrations.AddIndex(
            model_name='corporatebudget',
            index=models.Index(fields=['fiscalyear'], name='corporatebu_fiscaly_0c6f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatebudget',
            index=models.Index(fields=['statecode'], name='corporatebu_stateco_c32ed4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatebudget',
            unique_together={('fiscalyear',)},
        ),
        migrations.AddIndex(
            model_name='corporateallocation',
            index=models.Index(fields=['year', 'month'], name='corporateal_year_1b3c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateallocation',
            index=models.Index(fields=['statecode'], name='corporateal_stateco_2fe6f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporateallocation',
            unique_together={('corporatebudgetid', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='corporatebudgetversion',
            index=models.Index(fields=['corporatebudgetid', 'statecode'], name='corporatebu_corpora_23d24b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatebudgetversion',
            unique_together={('corporatebudgetid', 'versionnumber')},
        ),
        migrations.AddIndex(
            model_name='corporatebudgetline',
            index=models.Index(fields=['versionid'], name='corporatebu_version_bcceef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporatebudgetline',
            unique_together={('versionid', 'categorycode')},
        ),
        migrations.AddIndex(
            model_name='corporateexpense',
            index=models.Index(fields=['year', 'month'], name='corporateex_year_2886a9_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateexpense',
            index=models.Index(fields=['corporatebudgetid', 'year'], name='corporateex_corpora_0fae85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='corporateexpense',
            unique_together={('corporatebudgetid', 'categorycode', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='whatifsimulation',
            index=models.Index(fields=['fiscalyear'], name='whatifsimul_fiscaly_105665_idx'),
        ),
        migrations.AddIndex(
            model_name='whatifsimulation',
            index=models.Index(fields=['statecode'], name='whatifsimul_stateco_198c55_idx'),
        ),
    ]
