# Generated by Django 6.0.2 on 2026-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corporatebudget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='corporatebudget',
            name='periodtype',
            field=models.IntegerField(choices=[(0, 'Anual'), (1, 'Q1 (Ene-Mar)'), (2, 'Q2 (Abr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dic)')], db_column='periodtype', default=0),
        ),
        migrations.AddField(
            model_name='corporatebudget',
            name='quarter',
            field=models.IntegerField(blank=True, db_column='quarter', help_text='Quarter number (1-4) when periodtype is quarterly', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='corporatebudget',
            unique_together={('fiscalyear', 'periodtype', 'quarter')},
        ),
    ]
