# Generated by Django 5.0.1 on 2025-11-29 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('contactid', models.UUIDField(db_column='contactid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstname', max_length=50, null=True)),
                ('lastname', models.CharField(db_column='lastname', max_length=50)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=160)),
                ('emailaddress1', models.EmailField(blank=True, db_column='emailaddress1', max_length=100, null=True)),
                ('telephone1', models.CharField(blank=True, db_column='telephone1', max_length=50, null=True, verbose_name='Business Phone')),
                ('mobilephone', models.CharField(blank=True, db_column='mobilephone', max_length=50, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='jobtitle', max_length=100, null=True)),
                ('address1_line1', models.CharField(blank=True, db_column='address1_line1', max_length=250, null=True, verbose_name='Street 1')),
                ('address1_city', models.CharField(blank=True, db_column='address1_city', max_length=80, null=True, verbose_name='City')),
                ('address1_stateorprovince', models.CharField(blank=True, db_column='address1_stateorprovince', max_length=50, null=True, verbose_name='State/Province')),
                ('address1_postalcode', models.CharField(blank=True, db_column='address1_postalcode', max_length=20, null=True, verbose_name='ZIP/Postal Code')),
                ('address1_country', models.CharField(blank=True, db_column='address1_country', max_length=80, null=True, verbose_name='Country/Region')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_column='statuscode', default=1)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
                ('parentcustomerid', models.ForeignKey(blank=True, db_column='parentcustomerid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='accounts.account', verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['lastname', 'firstname'], name='contact_lastnam_0fbfc0_idx'), models.Index(fields=['fullname'], name='contact_fullnam_a659cc_idx'), models.Index(fields=['statecode', 'ownerid'], name='contact_stateco_f0184d_idx'), models.Index(fields=['emailaddress1'], name='contact_emailad_5eba3e_idx'), models.Index(fields=['parentcustomerid'], name='contact_parentc_f6471d_idx')],
            },
        ),
    ]
