# Generated by Django 5.0.1 on 2025-11-29 20:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('opportunities', '0002_opportunity_accountid_opportunity_contactid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('salesorderdetailid', models.UUIDField(db_column='salesorderdetailid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productname', max_length=100)),
                ('productdescription', models.TextField(blank=True, db_column='productdescription', null=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('priceperunit', models.DecimalField(db_column='priceperunit', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('manualdiscountamount', models.DecimalField(db_column='manualdiscountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('tax', models.DecimalField(db_column='tax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('baseamount', models.DecimalField(db_column='baseamount', decimal_places=2, max_digits=19)),
                ('extendedamount', models.DecimalField(db_column='extendedamount', decimal_places=2, max_digits=19)),
                ('sequencenumber', models.IntegerField(db_column='sequencenumber', default=1)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
            ],
            options={
                'db_table': 'salesorderdetail',
                'ordering': ['salesorderid', 'sequencenumber'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('salesorderid', models.UUIDField(db_column='salesorderid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('ordernumber', models.CharField(db_column='ordernumber', max_length=100, unique=True)),
                ('totalamount', models.DecimalField(db_column='totalamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totaldiscountamount', models.DecimalField(db_column='totaldiscountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totaltax', models.DecimalField(db_column='totaltax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totallineitemamount', models.DecimalField(db_column='totallineitemamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('requestdeliveryby', models.DateField(blank=True, db_column='requestdeliveryby', null=True)),
                ('datefulfilled', models.DateTimeField(blank=True, db_column='datefulfilled', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Submitted'), (2, 'Canceled'), (3, 'Fulfilled'), (4, 'Invoiced')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'In Progress'), (4, 'No Money'), (5, 'Complete'), (6, 'Partial'), (7, 'Canceled')], db_column='statuscode', default=1)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.account')),
                ('contactid', models.ForeignKey(blank=True, db_column='contactid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.contact')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('opportunityid', models.ForeignKey(blank=True, db_column='opportunityid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='opportunities.opportunity')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salesorder',
                'ordering': ['-createdon'],
            },
        ),
    ]
