# Generated by Django 5.0.1 on 2025-11-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='quoteid',
            field=models.ForeignKey(blank=True, db_column='quoteid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='salesorderid',
            field=models.ForeignKey(db_column='salesorderid', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.salesorder'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['statecode', 'ownerid'], name='salesorder_stateco_9c0ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['quoteid'], name='salesorder_quoteid_2611fb_idx'),
        ),
    ]
