# Generated by Django 6.0.2 on 2026-03-21 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('assign', 'Assign'), ('qualify', 'Qualify'), ('close', 'Close'), ('win', 'Win'), ('lose', 'Lose'), ('cancel', 'Cancel'), ('approve', 'Approve'), ('reject', 'Reject'), ('convert', 'Convert'), ('classify', 'Classify'), ('verify', 'Verify')], db_index=True, max_length=20)),
                ('entity', models.CharField(db_index=True, help_text='Entity type (e.g. lead, opportunity, quote)', max_length=50)),
                ('recordid', models.UUIDField(db_index=True, help_text='ID of the affected record')),
                ('recordname', models.CharField(blank=True, default='', help_text='Display name of the record at time of action', max_length=255)),
                ('username', models.CharField(blank=True, default='', help_text='Denormalized user fullname for fast display', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='List of {field, old, new} dicts for update actions', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Full snapshot before (for delete or critical changes)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Full snapshot after (for create or critical changes)', null=True)),
                ('message', models.CharField(blank=True, default='', help_text='Human-readable description of the action', max_length=500)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'recordid', '-timestamp'], name='idx_audit_entity_record'), models.Index(fields=['userid', '-timestamp'], name='idx_audit_user'), models.Index(fields=['action', '-timestamp'], name='idx_audit_action')],
            },
        ),
    ]
