# Generated by Django 6.0.2 on 2026-02-20 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('microsoft_user_id', models.CharField(help_text='Azure AD Object ID', max_length=255)),
                ('microsoft_email', models.EmailField(help_text='Microsoft account email (display only)', max_length=254)),
                ('token_cache', models.TextField(help_text='MSAL serialized token cache (contains access + refresh tokens)')),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
                ('last_sync_on', models.DateTimeField(blank=True, null=True)),
                ('last_sync_count', models.IntegerField(default=0)),
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Microsoft Token',
                'verbose_name_plural': 'Microsoft Tokens',
                'db_table': 'microsoft_token',
            },
        ),
    ]
