# Generated by Django 6.0.2 on 2026-02-21 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Token',
                'verbose_name_plural': 'SSO Tokens',
                'db_table': 'sso_token',
            },
        ),
    ]
