# Generated by Django 6.0.2 on 2026-03-12 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_customertypecode'),
        ('opportunities', '0002_opportunity_accountid_opportunity_contactid_and_more'),
        ('projects', '0003_teammember_link_systemuser'),
        ('proyeccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationProject',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('estimationprojectid', models.UUIDField(db_column='estimationprojectid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('estimationnumber', models.CharField(db_column='estimationnumber', max_length=20, unique=True)),
                ('presentationdate', models.DateField(blank=True, db_column='presentationdate', null=True)),
                ('estimatedstartdate', models.DateField(blank=True, db_column='estimatedstartdate', null=True)),
                ('estimatedenddate', models.DateField(blank=True, db_column='estimatedenddate', null=True)),
                ('durationmonths', models.IntegerField(db_column='durationmonths', default=0)),
                ('projecttype', models.IntegerField(db_column='projecttype', default=0)),
                ('biddingtype', models.IntegerField(db_column='biddingtype', default=0)),
                ('periodtype', models.IntegerField(db_column='periodtype', default=0)),
                ('estimatedcontractamount', models.DecimalField(db_column='estimatedcontractamount', decimal_places=2, default=0, max_digits=19)),
                ('exchangerate_mxn_usd', models.DecimalField(blank=True, db_column='exchangerate_mxn_usd', decimal_places=4, max_digits=12, null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Draft'), (1, 'In Review'), (2, 'Accepted'), (3, 'Converted'), (4, 'Canceled')], db_column='statecode', default=0)),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimation_projects', to='accounts.account')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generatedprojectid', models.ForeignKey(blank=True, db_column='generatedprojectid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimation', to='projects.constructionproject')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('opportunityid', models.ForeignKey(blank=True, db_column='opportunityid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_projects', to='opportunities.opportunity')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_estimation_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estimation Project',
                'verbose_name_plural': 'Estimation Projects',
                'db_table': 'estimationproject',
                'ordering': ['-createdon'],
            },
        ),
        migrations.AlterField(
            model_name='budgetconcept',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='budget_concepts', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='conceptfamily',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='concept_families', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='conceptsubfamily',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='concept_subfamilies', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='externalcostitem',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='external_costs', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='indirectcostdetail',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='indirect_cost_details', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='offeralternative',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='offer_alternatives', to='proyeccion.estimationproject'),
        ),
        migrations.AlterField(
            model_name='workplanentry',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='workplan_entries', to='proyeccion.estimationproject'),
        ),
        migrations.AddIndex(
            model_name='estimationproject',
            index=models.Index(fields=['name'], name='estimationp_name_bbd55a_idx'),
        ),
        migrations.AddIndex(
            model_name='estimationproject',
            index=models.Index(fields=['estimationnumber'], name='estimationp_estimat_07be32_idx'),
        ),
        migrations.AddIndex(
            model_name='estimationproject',
            index=models.Index(fields=['statecode', 'ownerid'], name='estimationp_stateco_c1fa37_idx'),
        ),
    ]
