# Generated by Django 6.0.2 on 2026-03-17 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0002_estimationproject_alter_budgetconcept_projectid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPriceCatalogItem',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('catalogitemid', models.UUIDField(db_column='catalogitemid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', help_text='Auto-generated or manual concept code', max_length=30, unique=True)),
                ('description', models.TextField(db_column='description', help_text='Full concept description')),
                ('unit', models.CharField(db_column='unit', max_length=20)),
                ('source', models.IntegerField(choices=[(0, 'SICT'), (1, 'Histórico'), (2, 'Manual')], db_column='source', default=1, help_text='Origin: SICT(0), Histórico(1), Manual(2)')),
                ('category', models.CharField(blank=True, db_column='category', default='', help_text='Optional grouping (Preliminares, Instalaciones, etc.)', max_length=200)),
                ('averageprice', models.DecimalField(db_column='averageprice', decimal_places=4, default=0, help_text='Computed average P.U. across all references', max_digits=19)),
                ('minprice', models.DecimalField(db_column='minprice', decimal_places=4, default=0, help_text='Minimum P.U. across all references', max_digits=19)),
                ('maxprice', models.DecimalField(db_column='maxprice', decimal_places=4, default=0, help_text='Maximum P.U. across all references', max_digits=19)),
                ('referencecount', models.IntegerField(db_column='referencecount', default=0, help_text='Number of project references for this concept')),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conceptpricecatalogitem',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConceptPriceReference',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('referenceid', models.UUIDField(db_column='referenceid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectname', models.CharField(db_column='projectname', help_text='Historical project name (e.g., Cumbres Elite, Swiss Lab Mty)', max_length=200)),
                ('projectlocation', models.CharField(blank=True, db_column='projectlocation', default='', max_length=300)),
                ('unitprice', models.DecimalField(db_column='unitprice', decimal_places=4, default=0, help_text='Precio Unitario in this project', max_digits=19)),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=4, help_text='Quantity used in this project', max_digits=19, null=True)),
                ('totalamount', models.DecimalField(blank=True, db_column='totalamount', decimal_places=4, help_text='Total amount (P.U. x quantity)', max_digits=19, null=True)),
                ('referencedate', models.DateField(blank=True, db_column='referencedate', null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=500)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('catalogitemid', models.ForeignKey(db_column='catalogitemid', on_delete=django.db.models.deletion.CASCADE, related_name='price_references', to='proyeccion.conceptpricecatalogitem')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conceptpricereference',
                'ordering': ['projectname'],
            },
        ),
        migrations.AddIndex(
            model_name='conceptpricecatalogitem',
            index=models.Index(fields=['source'], name='conceptpric_source_ddc1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptpricecatalogitem',
            index=models.Index(fields=['code'], name='conceptpric_code_9943d5_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptpricecatalogitem',
            index=models.Index(fields=['unit'], name='conceptpric_unit_12741f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptpricereference',
            index=models.Index(fields=['catalogitemid'], name='conceptpric_catalog_5a8a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptpricereference',
            index=models.Index(fields=['projectname'], name='conceptpric_project_656c74_idx'),
        ),
    ]
