# Generated by Django 6.0.2 on 2026-03-22 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SYSTEM_TEMPLATES = [
    {
        'name': 'SICT — Construcción de Carreteras',
        'description': '9 familias del tabulador SICT 2024 para obras de infraestructura carretera.',
        'category': 'infraestructura',
        'families': {
            'TER': ('Terracerías', [('01','Desmonte'),('02','Despalme'),('03','Cortes'),('04','Terraplenes'),('05','Subrasante')]),
            'PAV': ('Pavimentos', [('01','Sub-base y base'),('02','Carpeta asfáltica'),('03','Riegos'),('04','Concreto hidráulico')]),
            'EST': ('Estructuras', [('01','Cimentaciones'),('02','Subestructura'),('03','Superestructura'),('04','Acabados')]),
            'DRE': ('Drenaje y Subdrenaje', [('01','Alcantarillas'),('02','Cunetas y contracunetas'),('03','Subdrenaje'),('04','Obras complementarias')]),
            'SEÑ': ('Señalamiento y Seguridad', [('01','Señalamiento vertical'),('02','Señalamiento horizontal'),('03','Dispositivos de seguridad')]),
            'CIM': ('Cimentaciones', [('01','Pilotes'),('02','Pilas'),('03','Muros Milán')]),
            'TUN': ('Túneles', [('01','Excavación'),('02','Soporte y revestimiento')]),
            'SIT': ('Sistemas Inteligentes de Transporte', [('01','Equipamiento'),('02','Instalación')]),
            'OBM': ('Obras Marginales', [('01','Obras de protección'),('02','Obras de drenaje menor')]),
        },
    },
    {
        'name': 'Edificación General',
        'description': '8 familias estándar para proyectos de edificación (naves, oficinas, comercial).',
        'category': 'edificacion',
        'families': {
            'PRE': ('Preliminares', [('01','Trazo y nivelación'),('02','Desmonte y despalme'),('03','Demoliciones'),('04','Implantación de obra')]),
            'CIM': ('Cimentación', [('01','Excavaciones'),('02','Zapatas y dados'),('03','Trabes de liga'),('04','Firmes y pisos')]),
            'EES': ('Estructura', [('01','Columnas'),('02','Trabes'),('03','Losas'),('04','Muros de carga'),('05','Estructura metálica')]),
            'ALB': ('Albañilería', [('01','Muros divisorios'),('02','Castillos y cadenas'),('03','Aplanados y recubrimientos')]),
            'INS': ('Instalaciones', [('01','Hidráulica'),('02','Sanitaria'),('03','Eléctrica'),('04','Gas'),('05','Especiales')]),
            'ACA': ('Acabados', [('01','Pisos y losetas'),('02','Pintura'),('03','Cancelería y vidrio'),('04','Carpintería'),('05','Herrería')]),
            'EXT': ('Obras Exteriores', [('01','Banquetas y guarniciones'),('02','Jardines y áreas verdes'),('03','Estacionamiento'),('04','Bardas y cercados')]),
            'LIM': ('Limpieza y Entrega', [('01','Limpieza final'),('02','Retiro de escombros')]),
        },
    },
    {
        'name': 'Minería a Cielo Abierto',
        'description': '6 familias para proyectos de minería, presas de jales, y fortificación.',
        'category': 'mineria',
        'families': {
            'GAB': ('Gabinete', [('01','Proyecto ejecutivo'),('02','Estudios y permisos')]),
            'PRE': ('Preliminares', [('01','Trazo y nivelación topográfica'),('02','Deshierbe, desmonte y despalme'),('03','Implantación y retiro de equipo'),('04','Caminos de acceso')]),
            'MOV': ('Movimiento de Tierras', [('01','Corte en material común'),('02','Corte en roca'),('03','Carga y acarreo'),('04','Formación de terraplenes'),('05','Abatimiento de taludes')]),
            'FOR': ('Fortificación', [('01','Malla triple torsión'),('02','Anclajes y varilla'),('03','Concreto lanzado'),('04','Marcos metálicos'),('05','Geotextiles y geomembranas')]),
            'DRE': ('Drenaje y Control de Agua', [('01','Cunetas y contracunetas'),('02','Lavaderos'),('03','Pozos de absorción'),('04','Subdrenaje')]),
            'OBR': ('Obras Complementarias', [('01','Muros de contención'),('02','Gaviones'),('03','Bermas de seguridad')]),
        },
    },
    {
        'name': 'Obra Civil Simple',
        'description': '4 familias básicas para proyectos civiles menores.',
        'category': 'industrial',
        'families': {
            'PRE': ('Preliminares', [('01','Trazo y nivelación'),('02','Limpieza y preparación')]),
            'TER': ('Terracerías', [('01','Excavación'),('02','Relleno y compactación'),('03','Acarreos')]),
            'CON': ('Concretos y Acero', [('01','Cimbra'),('02','Acero de refuerzo'),('03','Concreto')]),
            'ACA': ('Acabados y Varios', [('01','Acabados'),('02','Limpieza final')]),
        },
    },
]


def seed_system_templates(apps, schema_editor):
    FTS = apps.get_model('proyeccion', 'FamilyTemplateSet')
    FTI = apps.get_model('proyeccion', 'FamilyTemplateItem')

    for tmpl in SYSTEM_TEMPLATES:
        ts = FTS.objects.create(
            name=tmpl['name'],
            description=tmpl['description'],
            category=tmpl['category'],
            issystem=True,
        )
        family_sort = 0
        for fcode, (fname, subs) in tmpl['families'].items():
            family_sort += 1
            sf_sort = 0
            for scode, sname in subs:
                sf_sort += 1
                FTI.objects.create(
                    templatesetid=ts,
                    familycode=fcode,
                    familyname=fname,
                    subfamilycode=scode,
                    subfamilyname=sname,
                    familysortorder=family_sort,
                    subfamilysortorder=sf_sort,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0003_add_concept_price_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTemplateSet',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('templatesetid', models.UUIDField(db_column='templatesetid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('category', models.CharField(db_column='category', default='custom', max_length=30)),
                ('issystem', models.BooleanField(db_column='issystem', default=False)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Template Set',
                'db_table': 'familytemplateset',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyTemplateItem',
            fields=[
                ('templateitemid', models.UUIDField(db_column='templateitemid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('familycode', models.CharField(db_column='familycode', max_length=10)),
                ('familyname', models.CharField(db_column='familyname', max_length=200)),
                ('subfamilycode', models.CharField(blank=True, db_column='subfamilycode', default='', max_length=10)),
                ('subfamilyname', models.CharField(blank=True, db_column='subfamilyname', default='', max_length=200)),
                ('familysortorder', models.IntegerField(db_column='familysortorder', default=0)),
                ('subfamilysortorder', models.IntegerField(db_column='subfamilysortorder', default=0)),
                ('statecode', models.IntegerField(db_column='statecode', default=0)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('templatesetid', models.ForeignKey(db_column='templatesetid', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyeccion.familytemplateset')),
            ],
            options={
                'db_table': 'familytemplateitem',
                'ordering': ['familysortorder', 'familycode', 'subfamilysortorder'],
                'unique_together': {('templatesetid', 'familycode', 'subfamilycode')},
            },
        ),
        migrations.RunPython(seed_system_templates, migrations.RunPython.noop),
    ]
