# Generated by Django 6.0.2 on 2026-03-22 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0004_add_family_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetconcept',
            index=models.Index(fields=['projectid', 'statecode'], name='budgetconce_project_6d9a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcostitem',
            index=models.Index(fields=['projectid'], name='externalcos_project_2cdda0_idx'),
        ),
        migrations.AddIndex(
            model_name='familytemplateset',
            index=models.Index(fields=['statecode'], name='familytempl_stateco_be2b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='indirectcostdetail',
            index=models.Index(fields=['projectid', 'statecode'], name='indirectcos_project_bb8630_idx'),
        ),
        migrations.AddIndex(
            model_name='offeralternative',
            index=models.Index(fields=['projectid', 'statecode'], name='offeraltern_project_e0e0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='unitcostbreakdown',
            index=models.Index(fields=['conceptid', 'statecode'], name='unitcostbre_concept_5dc941_idx'),
        ),
        migrations.AddIndex(
            model_name='workplanentry',
            index=models.Index(fields=['projectid'], name='workplanent_project_efaced_idx'),
        ),
    ]
