# Generated by Django 5.0.1 on 2026-04-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0006_add_classification_columns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conceptpricecatalogitem',
            new_name='conceptpric_classif_1bb653_idx',
            old_name='conceptpric_classif_l2_idx',
        ),
        migrations.AlterField(
            model_name='conceptfamily',
            name='code',
            field=models.CharField(db_column='code', max_length=50),
        ),
        migrations.AlterField(
            model_name='conceptsubfamily',
            name='code',
            field=models.CharField(db_column='code', max_length=50),
        ),
    ]
