# Generated by Django 5.0.1 on 2026-04-23 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0008_workplan_entrytype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionPeriod',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('periodid', models.UUIDField(db_column='periodid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodnumber', models.IntegerField(db_column='periodnumber')),
                ('periodlabel', models.CharField(db_column='periodlabel', max_length=20)),
                ('startdate', models.DateField(db_column='startdate')),
                ('enddate', models.DateField(db_column='enddate')),
                ('periodtype', models.IntegerField(db_column='periodtype')),
            ],
            options={
                'db_table': 'projectionperiod',
                'ordering': ['periodnumber'],
            },
        ),
        migrations.RenameIndex(
            model_name='workplanentry',
            new_name='workplanent_project_623747_idx',
            old_name='workplanent_project_etype_idx',
        ),
        migrations.AddField(
            model_name='estimationproject',
            name='periodcount',
            field=models.IntegerField(db_column='periodcount', default=0),
        ),
        migrations.AddField(
            model_name='projectionperiod',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectionperiod',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectionperiod',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='projection_periods', to='proyeccion.estimationproject'),
        ),
        migrations.AddIndex(
            model_name='projectionperiod',
            index=models.Index(fields=['projectid', 'periodnumber'], name='projectionp_project_011e53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectionperiod',
            unique_together={('projectid', 'periodnumber')},
        ),
    ]
