# Generated by Django 5.0.1 on 2026-04-23 00:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0009_projection_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDistribution',
            fields=[
                ('distributionid', models.UUIDField(db_column='distributionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linetype', models.IntegerField(choices=[(0, 'Direct Cost (UnitCostBreakdown)'), (1, 'Indirect Cost (IndirectCostDetail)')], db_column='linetype')),
                ('periodnumber', models.IntegerField(db_column='periodnumber')),
                ('fraction', models.DecimalField(db_column='fraction', decimal_places=8, default=Decimal('0'), max_digits=10)),
                ('isderived', models.BooleanField(db_column='isderived', default=True)),
                ('version', models.IntegerField(db_column='version', default=0)),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('breakdownid', models.ForeignKey(blank=True, db_column='breakdownid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_distributions', to='proyeccion.unitcostbreakdown')),
                ('indirectcostid', models.ForeignKey(blank=True, db_column='indirectcostid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_distributions', to='proyeccion.indirectcostdetail')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='cost_distributions', to='proyeccion.estimationproject')),
            ],
            options={
                'db_table': 'costdistribution',
                'indexes': [models.Index(fields=['projectid', 'periodnumber'], name='costdistrib_project_7eeb64_idx'), models.Index(fields=['projectid', 'linetype'], name='costdistrib_project_809efd_idx'), models.Index(fields=['breakdownid'], name='costdistrib_breakdo_3d5611_idx'), models.Index(fields=['indirectcostid'], name='costdistrib_indirec_a564a0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='costdistribution',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('breakdownid__isnull', False), ('indirectcostid__isnull', True), ('linetype', 0)), models.Q(('breakdownid__isnull', True), ('indirectcostid__isnull', False), ('linetype', 1)), _connector='OR'), name='cost_distribution_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='costdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('breakdownid__isnull', False)), fields=('breakdownid', 'periodnumber'), name='uq_distribution_breakdown_period'),
        ),
        migrations.AddConstraint(
            model_name='costdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('indirectcostid__isnull', False)), fields=('indirectcostid', 'periodnumber'), name='uq_distribution_indirect_period'),
        ),
        migrations.AddConstraint(
            model_name='costdistribution',
            constraint=models.CheckConstraint(check=models.Q(('fraction__gte', 0), ('fraction__lte', 1)), name='cost_distribution_fraction_range'),
        ),
    ]
