# Generated by Django 5.0.1 on 2026-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0010_cost_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectcostdetail',
            name='endmonth',
            field=models.IntegerField(blank=True, db_column='endmonth', help_text='Last period (1-based) where this cost applies. null = until last.', null=True),
        ),
        migrations.AddField(
            model_name='indirectcostdetail',
            name='startmonth',
            field=models.IntegerField(blank=True, db_column='startmonth', help_text='First period (1-based) where this cost applies. null = from P1.', null=True),
        ),
    ]
