# Generated by Django 5.0.1 on 2026-04-23 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0011_indirect_cost_monthrange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPresence',
            fields=[
                ('presenceid', models.UUIDField(db_column='presenceid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('viewing', 'Viewing'), ('editing', 'Editing')], db_column='mode', max_length=16)),
                ('last_seen', models.DateTimeField(auto_now=True, db_column='last_seen')),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='distribution_presence', to='proyeccion.estimationproject')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distributionpresence',
                'indexes': [models.Index(fields=['projectid', 'last_seen'], name='distributio_project_93ab69_idx')],
                'unique_together': {('projectid', 'userid')},
            },
        ),
    ]
