# Generated by Django 6.0.2 on 2026-04-25 13:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0012_distribution_presence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationFinancialSettings',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('settingsid', models.UUIDField(db_column='settingsid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advanceamountnotax', models.DecimalField(db_column='advanceamountnotax', decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('advanceentryperiod', models.IntegerField(db_column='advanceentryperiod', default=1)),
                ('advanceamortizationrate', models.DecimalField(db_column='advanceamortizationrate', decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('imssretentionrate', models.DecimalField(db_column='imssretentionrate', decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('otherretentionrate', models.DecimalField(db_column='otherretentionrate', decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('retentionreturnperiod', models.IntegerField(blank=True, db_column='retentionreturnperiod', null=True)),
                ('directpaymentlag', models.IntegerField(db_column='directpaymentlag', default=0)),
                ('indirectpaymentlag', models.IntegerField(db_column='indirectpaymentlag', default=0)),
                ('financecostrate', models.DecimalField(db_column='financecostrate', decimal_places=6, default=Decimal('0.001000'), max_digits=7)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.OneToOneField(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='proyeccion.estimationproject')),
            ],
            options={
                'verbose_name': 'Estimation Financial Settings',
                'verbose_name_plural': 'Estimation Financial Settings',
                'db_table': 'estimationfinancialsettings',
            },
        ),
    ]
