# Generated by Django 6.0.2 on 2026-04-25 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0013_estimationfinancialsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationBillingRule',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('ruleid', models.UUIDField(db_column='ruleid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(db_column='sequence')),
                ('percent', models.DecimalField(db_column='percent', decimal_places=4, max_digits=5)),
                ('lagperiods', models.IntegerField(db_column='lagperiods')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='billing_rules', to='proyeccion.estimationproject')),
            ],
            options={
                'verbose_name': 'Estimation Billing Rule',
                'verbose_name_plural': 'Estimation Billing Rules',
                'db_table': 'estimationbillingrule',
                'ordering': ['projectid', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('projectid', 'sequence'), name='uniq_estimation_billing_seq'), models.CheckConstraint(condition=models.Q(('sequence__gte', 1), ('sequence__lte', 10)), name='estimation_billing_seq_range'), models.CheckConstraint(condition=models.Q(('percent__gte', 0), ('percent__lte', 1)), name='estimation_billing_pct_range'), models.CheckConstraint(condition=models.Q(('lagperiods__gte', 0), ('lagperiods__lte', 120)), name='estimation_billing_lag_range')],
            },
        ),
    ]
