# Generated by Django 6.0.2 on 2026-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0014_estimationbillingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationfinancialsettings',
            name='category_lags',
            field=models.JSONField(blank=True, db_column='category_lags', default=dict),
        ),
    ]
