# Generated by Django 6.0.2 on 2026-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0015_estimationfinancialsettings_category_lags'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectcostdetail',
            name='lineversion',
            field=models.IntegerField(db_column='lineversion', default=0, help_text='Optimistic lock para edits a nivel de línea (lag).'),
        ),
        migrations.AddField(
            model_name='indirectcostdetail',
            name='paymentlagperiods',
            field=models.IntegerField(blank=True, db_column='paymentlagperiods', help_text='Lag de pago en periodos del proyecto. NULL = usa el default global (indirectpaymentlag).', null=True),
        ),
        migrations.AddField(
            model_name='unitcostbreakdown',
            name='lineversion',
            field=models.IntegerField(db_column='lineversion', default=0, help_text='Optimistic lock para edits a nivel de línea (lag).'),
        ),
        migrations.AddField(
            model_name='unitcostbreakdown',
            name='paymentlagperiods',
            field=models.IntegerField(blank=True, db_column='paymentlagperiods', help_text='Lag de pago en periodos del proyecto. NULL = usa el default global (directpaymentlag).', null=True),
        ),
    ]
