# Generated by Django 6.0.2 on 2026-04-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0016_add_paymentlagperiods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationfinancialsettings',
            name='category_lags',
        ),
    ]
