# Generated by Django 6.0.2 on 2026-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0017_drop_category_lags'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationproject',
            name='profitpercent',
            field=models.DecimalField(db_column='profitpercent', decimal_places=2, default=0, max_digits=5),
        ),
    ]
