# Generated by Django 6.0.2 on 2026-05-01 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0018_add_estimationproject_profitpercent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='costdistribution',
            index=models.Index(fields=['projectid', 'breakdownid'], name='costdistrib_project_86f55c_idx'),
        ),
        migrations.AddIndex(
            model_name='costdistribution',
            index=models.Index(fields=['projectid', 'indirectcostid'], name='costdistrib_project_246e39_idx'),
        ),
    ]
