# Generated by Django 6.0.2 on 2026-06-01 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0019_add_costdistribution_compound_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcostitem',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalcostitem',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familytemplateitem',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familytemplateitem',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitcostbreakdown',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitcostbreakdown',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalcostitem',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='externalcostitem',
            name='modifiedon',
            field=models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='familytemplateitem',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='familytemplateitem',
            name='modifiedon',
            field=models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='unitcostbreakdown',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='unitcostbreakdown',
            name='modifiedon',
            field=models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified'),
        ),
    ]
