# Generated by Django 6.0.2 on 2026-06-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0020_externalcostitem_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectcostdetail',
            name='formulakey',
            field=models.CharField(blank=True, db_column='formulakey', default='', help_text='Marca líneas generadas por la calculadora de fianzas/impuestos (bond_anticipo, bond_cumplimiento, bond_vicios, insurance_rc, tax_isr). Vacío = línea capturada manualmente.', max_length=30),
        ),
    ]
