# Generated by Django 6.0.2 on 2026-06-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0021_indirectcost_formulakey'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectcostdetail',
            name='applies',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Yes'), (2, 'No')], db_column='applies', default=1, help_text='SI/NO/NA. Solo significativo para externos (C7/C8). Líneas internas C1-C6 quedan en SI. Semillas del checklist se siembran en NA.'),
        ),
        migrations.AddField(
            model_name='indirectcostdetail',
            name='percentofsale',
            field=models.DecimalField(blank=True, db_column='percentofsale', decimal_places=4, help_text='Si no es null, la línea es %-driven: amount = (%/100) × contrato. null = amount por mensual×uds×meses (o por la calculadora).', max_digits=7, null=True),
        ),
    ]
