# Generated by Django 6.0.2 on 2026-06-02 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0023_unify_external_into_indirect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offeralternative',
            name='directadjustmenttotal',
            field=models.DecimalField(db_column='directadjustmenttotal', decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='offeralternative',
            name='indirectadjustmenttotal',
            field=models.DecimalField(db_column='indirectadjustmenttotal', decimal_places=2, default=0, max_digits=19),
        ),
        migrations.CreateModel(
            name='AlternativeCostAdjustment',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('adjustmentid', models.UUIDField(db_column='adjustmentid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costtype', models.IntegerField(choices=[(0, 'Directo'), (1, 'Indirecto')], db_column='costtype')),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=300)),
                ('monthlyamount', models.DecimalField(db_column='monthlyamount', decimal_places=2, default=0, help_text='Monto mensual con signo (ej. -10000).', max_digits=19)),
                ('months', models.IntegerField(db_column='months', default=0)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, help_text='Delta derivado = monthlyamount × months.', max_digits=19)),
                ('sortorder', models.IntegerField(db_column='sortorder', default=0)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('alternativeid', models.ForeignKey(db_column='alternativeid', on_delete=django.db.models.deletion.CASCADE, related_name='cost_adjustments', to='proyeccion.offeralternative')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alternativecostadjustment',
                'ordering': ['costtype', 'sortorder'],
                'indexes': [models.Index(fields=['alternativeid', 'costtype'], name='alternative_alterna_a6edf0_idx')],
            },
        ),
    ]
