# Generated by Django 6.0.2 on 2026-06-12 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0024_alternative_cost_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationVersion',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('versionid', models.UUIDField(db_column='versionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versionnumber', models.IntegerField(db_column='versionnumber')),
                ('note', models.CharField(blank=True, db_column='note', default='', max_length=500)),
                ('isauto', models.BooleanField(db_column='isauto', default=False)),
                ('schema_version', models.IntegerField(db_column='schemaversion')),
                ('saleamount', models.DecimalField(db_column='saleamount', decimal_places=2, default=0, max_digits=19)),
                ('directtotal', models.DecimalField(db_column='directtotal', decimal_places=2, default=0, max_digits=19)),
                ('indirecttotal', models.DecimalField(db_column='indirecttotal', decimal_places=2, default=0, max_digits=19)),
                ('margintotal', models.DecimalField(db_column='margintotal', decimal_places=2, default=0, max_digits=19)),
                ('conceptcount', models.IntegerField(db_column='conceptcount', default=0)),
                ('snapshot', models.JSONField(db_column='snapshot')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='proyeccion.estimationproject')),
            ],
            options={
                'db_table': 'estimationversion',
                'ordering': ['-versionnumber'],
                'indexes': [models.Index(fields=['projectid', '-versionnumber'], name='estimationv_project_8c5891_idx')],
                'unique_together': {('projectid', 'versionnumber')},
            },
        ),
    ]
