# Generated by Django 6.0.2 on 2026-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0025_estimationversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetconcept',
            name='description',
            field=models.TextField(db_column='description'),
        ),
        migrations.AlterField(
            model_name='indirectcostdetail',
            name='description',
            field=models.TextField(db_column='description'),
        ),
        migrations.AlterField(
            model_name='unitcostbreakdown',
            name='description',
            field=models.TextField(db_column='description'),
        ),
    ]
