# Generated by Django 6.0.2 on 2026-06-22 23:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccion', '0026_alter_budgetconcept_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroDistribution',
            fields=[
                ('retirodistributionid', models.UUIDField(db_column='retirodistributionid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.IntegerField(choices=[(0, 'Retiro Transversal'), (1, 'Retiro Utilidad')], db_column='kind')),
                ('periodnumber', models.IntegerField(db_column='periodnumber')),
                ('fraction', models.DecimalField(db_column='fraction', decimal_places=8, default=Decimal('0'), max_digits=10)),
                ('isderived', models.BooleanField(db_column='isderived', default=True)),
                ('version', models.IntegerField(db_column='version', default=0)),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='retiro_distributions', to='proyeccion.estimationproject')),
            ],
            options={
                'db_table': 'retirodistribution',
                'indexes': [models.Index(fields=['projectid', 'kind'], name='retirodistr_project_cfedd0_idx'), models.Index(fields=['projectid', 'periodnumber'], name='retirodistr_project_772294_idx')],
                'constraints': [models.UniqueConstraint(fields=('projectid', 'kind', 'periodnumber'), name='uq_retiro_project_kind_period'), models.CheckConstraint(condition=models.Q(('fraction__gte', 0), ('fraction__lte', 1)), name='retiro_distribution_fraction_range')],
            },
        ),
    ]
