# Generated by Django 5.0.1 on 2025-11-29 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('accountid', models.UUIDField(db_column='accountid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=160)),
                ('accountnumber', models.CharField(blank=True, db_column='accountnumber', max_length=20, null=True, unique=True)),
                ('emailaddress1', models.EmailField(blank=True, db_column='emailaddress1', max_length=100, null=True)),
                ('telephone1', models.CharField(blank=True, db_column='telephone1', max_length=50, null=True, verbose_name='Main Phone')),
                ('websiteurl', models.URLField(blank=True, db_column='websiteurl', null=True, verbose_name='Website')),
                ('address1_line1', models.CharField(blank=True, db_column='address1_line1', max_length=250, null=True, verbose_name='Street 1')),
                ('address1_city', models.CharField(blank=True, db_column='address1_city', max_length=80, null=True, verbose_name='City')),
                ('address1_stateorprovince', models.CharField(blank=True, db_column='address1_stateorprovince', max_length=50, null=True, verbose_name='State/Province')),
                ('address1_postalcode', models.CharField(blank=True, db_column='address1_postalcode', max_length=20, null=True, verbose_name='ZIP/Postal Code')),
                ('address1_country', models.CharField(blank=True, db_column='address1_country', max_length=80, null=True, verbose_name='Country/Region')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('revenue', models.DecimalField(blank=True, db_column='revenue', decimal_places=2, max_digits=19, null=True, verbose_name='Annual Revenue')),
                ('numberofemployees', models.IntegerField(blank=True, db_column='numberofemployees', null=True, verbose_name='Number of Employees')),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_column='statuscode', default=1)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['name'], name='account_name_a89769_idx'), models.Index(fields=['statecode', 'ownerid'], name='account_stateco_ee0ca6_idx'), models.Index(fields=['accountnumber'], name='account_account_a6fcd5_idx')],
            },
        ),
    ]
