# Generated by Django 6.0.2 on 2026-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customertypecode',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Supplier'), (3, 'Both')], db_column='customertypecode', default=1),
        ),
    ]
