# Generated by Django 6.0.2 on 2026-03-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_customertypecode'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountcategorycode',
            field=models.IntegerField(blank=True, db_column='accountcategorycode', null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='account',
            name='address1_line2',
            field=models.CharField(blank=True, db_column='address1_line2', max_length=250, null=True, verbose_name='Street 2'),
        ),
        migrations.AddField(
            model_name='account',
            name='creditlimit',
            field=models.DecimalField(blank=True, db_column='creditlimit', decimal_places=2, max_digits=19, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='account',
            name='creditonhold',
            field=models.BooleanField(db_column='creditonhold', default=False, verbose_name='Credit On Hold'),
        ),
        migrations.AddField(
            model_name='account',
            name='fax',
            field=models.CharField(blank=True, db_column='fax', max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='account',
            name='industrycode',
            field=models.IntegerField(blank=True, db_column='industrycode', null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='account',
            name='parentaccountid',
            field=models.ForeignKey(blank=True, db_column='parentaccountid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounts.account', verbose_name='Parent Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='primarycontactid',
            field=models.ForeignKey(blank=True, db_column='primarycontactid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_account', to='contacts.contact', verbose_name='Primary Contact'),
        ),
        migrations.AddField(
            model_name='account',
            name='telephone2',
            field=models.CharField(blank=True, db_column='telephone2', max_length=50, null=True, verbose_name='Other Phone'),
        ),
    ]
