# Generated by Django 5.0.1 on 2025-11-28 23:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('leadid', models.UUIDField(db_column='leadid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstname', max_length=50, null=True)),
                ('lastname', models.CharField(db_column='lastname', max_length=50)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=160)),
                ('emailaddress1', models.EmailField(blank=True, db_column='emailaddress1', max_length=100, null=True)),
                ('telephone1', models.CharField(blank=True, db_column='telephone1', max_length=50, null=True, verbose_name='Business Phone')),
                ('mobilephone', models.CharField(blank=True, db_column='mobilephone', max_length=50, null=True)),
                ('companyname', models.CharField(blank=True, db_column='companyname', max_length=100, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='jobtitle', max_length=100, null=True)),
                ('subject', models.CharField(blank=True, db_column='subject', max_length=300, null=True, verbose_name='Topic')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('leadqualitycode', models.IntegerField(blank=True, choices=[(1, 'Cold'), (2, 'Warm'), (3, 'Hot')], db_column='leadqualitycode', null=True, verbose_name='Rating')),
                ('leadsourcecode', models.IntegerField(blank=True, choices=[(1, 'Advertisement'), (2, 'Employee Referral'), (3, 'External Referral'), (4, 'Partner'), (5, 'Public Relations'), (6, 'Seminar'), (7, 'Trade Show'), (8, 'Web'), (9, 'Word of Mouth'), (10, 'Other')], db_column='leadsourcecode', null=True, verbose_name='Lead Source')),
                ('statecode', models.IntegerField(choices=[(0, 'Open'), (1, 'Qualified'), (2, 'Disqualified')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'New'), (2, 'Contacted'), (3, 'Qualified'), (4, 'Lost'), (5, 'Cannot Contact'), (6, 'No Longer Interested')], db_column='statuscode', default=1)),
                ('estimatedvalue', models.DecimalField(blank=True, db_column='estimatedvalue', decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Est. Value')),
                ('estimatedclosedate', models.DateField(blank=True, db_column='estimatedclosedate', null=True, verbose_name='Est. Close Date')),
                ('qualifyingopportunityid', models.UUIDField(blank=True, db_column='qualifyingopportunityid', help_text='Opportunity created when this lead was qualified', null=True)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'lead',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['statecode', 'ownerid'], name='lead_stateco_449f6e_idx'), models.Index(fields=['statuscode'], name='lead_statusc_85334a_idx'), models.Index(fields=['emailaddress1'], name='lead_emailad_03e69d_idx'), models.Index(fields=['ownerid', 'statecode'], name='lead_ownerid_648144_idx'), models.Index(fields=['createdon'], name='lead_created_ef0e48_idx')],
            },
        ),
    ]
