# Generated by Django 6.0.2 on 2026-03-01 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImputationCode',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('imputationcodeid', models.UUIDField(db_column='imputationcodeid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costtype', models.IntegerField(choices=[(0, 'Direct'), (1, 'Indirect')], db_column='costtype')),
                ('code', models.CharField(db_column='code', max_length=20)),
                ('sequencenumber', models.IntegerField(db_column='sequencenumber')),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('estimatedsupplier', models.CharField(blank=True, db_column='estimatedsupplier', max_length=200, null=True)),
                ('unitcost', models.DecimalField(blank=True, db_column='unitcost', decimal_places=2, max_digits=19, null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=12, null=True)),
                ('executionmonths', models.IntegerField(blank=True, db_column='executionmonths', null=True)),
                ('totalbudget', models.DecimalField(db_column='totalbudget', decimal_places=2, default=0, max_digits=19)),
                ('personnelname', models.CharField(blank=True, db_column='personnelname', max_length=200, null=True)),
                ('personnelrole', models.CharField(blank=True, db_column='personnelrole', max_length=100, null=True)),
                ('personneltype', models.IntegerField(blank=True, choices=[(0, 'Office Staff'), (1, 'Field Staff')], db_column='personneltype', null=True)),
                ('monthlycost', models.DecimalField(blank=True, db_column='monthlycost', decimal_places=2, max_digits=19, null=True)),
                ('units', models.DecimalField(blank=True, db_column='units', decimal_places=2, max_digits=8, null=True)),
                ('totalspent', models.DecimalField(db_column='totalspent', decimal_places=2, default=0, max_digits=19)),
                ('remainingbudget', models.DecimalField(db_column='remainingbudget', decimal_places=2, default=0, max_digits=19)),
                ('percentused', models.DecimalField(db_column='percentused', decimal_places=2, default=0, max_digits=7)),
                ('statecode', models.IntegerField(db_column='statecode', default=0)),
            ],
            options={
                'db_table': 'imputationcode',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImputationPeriod',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('periodid', models.UUIDField(db_column='periodid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodtype', models.IntegerField(choices=[(0, 'Weekly'), (1, 'Fortnightly')], db_column='periodtype')),
                ('year', models.IntegerField(db_column='year')),
                ('month', models.IntegerField(db_column='month')),
                ('periodnumber', models.IntegerField(db_column='periodnumber')),
                ('label', models.CharField(db_column='label', max_length=30)),
                ('startdate', models.DateField(db_column='startdate')),
                ('enddate', models.DateField(db_column='enddate')),
                ('sortorder', models.IntegerField(db_column='sortorder', default=0)),
                ('statecode', models.IntegerField(db_column='statecode', default=0)),
            ],
            options={
                'db_table': 'imputationperiod',
                'ordering': ['sortorder'],
            },
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('categoryid', models.UUIDField(db_column='categoryid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costtype', models.IntegerField(choices=[(0, 'Direct'), (1, 'Indirect')], db_column='costtype')),
                ('code', models.CharField(db_column='code', max_length=5)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('statecode', models.IntegerField(db_column='statecode', default=0)),
                ('sortorder', models.IntegerField(db_column='sortorder', default=0)),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'costcategory',
                'ordering': ['sortorder', 'code'],
            },
        ),
    ]
