# Generated by Django 6.0.2 on 2026-03-01 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='cost_categories', to='projects.constructionproject'),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='categoryid',
            field=models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.PROTECT, related_name='imputation_codes', to='budgets.costcategory'),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='imputation_codes', to='projects.constructionproject'),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zoneid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputation_codes', to='projects.projectzone'),
        ),
        migrations.AddField(
            model_name='imputationperiod',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputationperiod',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputationperiod',
            name='projectid',
            field=models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='imputation_periods', to='projects.constructionproject'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['projectid', 'costtype'], name='costcategor_project_0f4c77_idx'),
        ),
        migrations.AddIndex(
            model_name='costcategory',
            index=models.Index(fields=['statecode'], name='costcategor_stateco_759954_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcategory',
            unique_together={('projectid', 'code')},
        ),
        migrations.AddIndex(
            model_name='imputationcode',
            index=models.Index(fields=['projectid', 'costtype'], name='imputationc_project_180f39_idx'),
        ),
        migrations.AddIndex(
            model_name='imputationcode',
            index=models.Index(fields=['projectid', 'categoryid'], name='imputationc_project_b9e083_idx'),
        ),
        migrations.AddIndex(
            model_name='imputationcode',
            index=models.Index(fields=['statecode'], name='imputationc_stateco_cc2b95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imputationcode',
            unique_together={('projectid', 'code')},
        ),
        migrations.AddIndex(
            model_name='imputationperiod',
            index=models.Index(fields=['projectid', 'year', 'month'], name='imputationp_project_249a37_idx'),
        ),
        migrations.AddIndex(
            model_name='imputationperiod',
            index=models.Index(fields=['statecode'], name='imputationp_stateco_cb6c2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imputationperiod',
            unique_together={('projectid', 'year', 'month', 'periodnumber')},
        ),
    ]
