# Generated by Django 6.0.2 on 2026-04-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_add_imputationcodebudget'),
        ('proyeccion', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imputationcodebudget',
            name='unique_code_period_budget',
        ),
        migrations.RenameIndex(
            model_name='imputationcodebudget',
            new_name='imputationc_imputat_c0613a_idx',
            old_name='idx_codebudget_code_period',
        ),
        migrations.RenameIndex(
            model_name='imputationcodebudget',
            new_name='imputationc_periodi_85a757_idx',
            old_name='idx_codebudget_period',
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='contractcode',
            field=models.CharField(blank=True, db_column='contractcode', help_text='Original concept code from estimation (A1, A2, B1, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='contractunitprice',
            field=models.DecimalField(blank=True, db_column='contractunitprice', decimal_places=4, help_text='Client unit price from contract/estimation', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='sourceconceptid',
            field=models.ForeignKey(blank=True, db_column='sourceconceptid', help_text='Original BudgetConcept from estimation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to='proyeccion.budgetconcept'),
        ),
        migrations.AddField(
            model_name='imputationcode',
            name='unit',
            field=models.CharField(blank=True, db_column='unit', help_text='Unit of measurement (PZA, m3, ml, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imputationcodebudget',
            name='actualvolume',
            field=models.DecimalField(db_column='actualvolume', decimal_places=4, default=0, help_text='Actual production volume in units for this period', max_digits=19),
        ),
        migrations.AddField(
            model_name='imputationcodebudget',
            name='plannedvolume',
            field=models.DecimalField(db_column='plannedvolume', decimal_places=4, default=0, help_text='Planned production volume in units for this period', max_digits=19),
        ),
        migrations.AlterUniqueTogether(
            name='imputationcodebudget',
            unique_together={('imputationcodeid', 'periodlabel')},
        ),
    ]
