# Generated by Django 6.0.2 on 2026-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_imputationcodebudget_unique_code_period_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='defaultpaymentlag',
            field=models.IntegerField(db_column='defaultpaymentlag', default=0, help_text='Default payment lag in periods for codes in this category'),
        ),
    ]
