# Generated by Django 6.0.2 on 2026-04-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_costcategory_defaultpaymentlag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationcode',
            name='paymentlagperiods',
            field=models.IntegerField(blank=True, db_column='paymentlagperiods', help_text='Payment lag in periods; NULL inherits from category.defaultpaymentlag', null=True),
        ),
    ]
