# Generated by Django 5.0.1 on 2025-12-16 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityid', models.UUIDField(db_column='activityid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activitytypecode', models.CharField(choices=[('email', 'Email'), ('phonecall', 'Phone Call'), ('task', 'Task'), ('appointment', 'Appointment')], db_column='activitytypecode', max_length=20)),
                ('statecode', models.IntegerField(choices=[(0, 'Open'), (1, 'Completed'), (2, 'Canceled'), (3, 'Scheduled')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(blank=True, db_column='statuscode', null=True)),
                ('subject', models.CharField(db_column='subject', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('regardingobjectid', models.UUIDField(blank=True, db_column='regardingobjectid', help_text='ID of the related entity (Lead, Opportunity, Account, Contact)', null=True)),
                ('regardingobjectidtype', models.CharField(blank=True, db_column='regardingobjectidtype', help_text='Type of the related entity (lead, opportunity, account, contact)', max_length=50, null=True)),
                ('scheduledstart', models.DateTimeField(blank=True, db_column='scheduledstart', null=True)),
                ('scheduledend', models.DateTimeField(blank=True, db_column='scheduledend', null=True)),
                ('actualdurationminutes', models.IntegerField(blank=True, db_column='actualdurationminutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actualstart', models.DateTimeField(blank=True, db_column='actualstart', null=True)),
                ('actualend', models.DateTimeField(blank=True, db_column='actualend', null=True)),
                ('prioritycode', models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], db_column='prioritycode', default=1, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_modified', to=settings.AUTH_USER_MODEL)),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='activities_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activitypointer',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('activity', models.OneToOneField(db_column='activityid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appointment_details', serialize=False, to='activities.activity')),
                ('location', models.CharField(blank=True, db_column='location', max_length=200, null=True)),
                ('requiredattendees', models.TextField(blank=True, db_column='requiredattendees', help_text='JSON array of Contact IDs', null=True)),
                ('optionalattendees', models.TextField(blank=True, db_column='optionalattendees', help_text='JSON array of Contact IDs', null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('activity', models.OneToOneField(db_column='activityid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_details', serialize=False, to='activities.activity')),
                ('to', models.TextField(blank=True, db_column='to', help_text='Recipient email addresses (semicolon separated)', null=True)),
                ('sender', models.CharField(blank=True, db_column='from', help_text='Sender email address', max_length=255, null=True)),
                ('cc', models.TextField(blank=True, db_column='cc', help_text='CC email addresses (semicolon separated)', null=True)),
                ('bcc', models.TextField(blank=True, db_column='bcc', help_text='BCC email addresses (semicolon separated)', null=True)),
                ('body', models.TextField(blank=True, db_column='body', null=True)),
                ('directioncode', models.BooleanField(db_column='directioncode', default=True, help_text='True=Outgoing, False=Incoming')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('activity', models.OneToOneField(db_column='activityid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phonecall_details', serialize=False, to='activities.activity')),
                ('phonenumber', models.CharField(blank=True, db_column='phonenumber', max_length=50, null=True)),
                ('directioncode', models.BooleanField(db_column='directioncode', default=True, help_text='True=Outgoing, False=Incoming')),
            ],
            options={
                'verbose_name': 'Phone Call',
                'verbose_name_plural': 'Phone Calls',
                'db_table': 'phonecall',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('activity', models.OneToOneField(db_column='activityid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_details', serialize=False, to='activities.activity')),
                ('percentcomplete', models.IntegerField(db_column='percentcomplete', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['statecode'], name='activitypoi_stateco_75102f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['ownerid'], name='activitypoi_ownerid_aede5f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activitytypecode'], name='activitypoi_activit_dfef96_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['regardingobjectid', 'regardingobjectidtype'], name='activitypoi_regardi_c388aa_idx'),
        ),
    ]
