# Generated by Django 6.0.2 on 2026-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytypecode',
            field=models.CharField(choices=[('email', 'Email'), ('phonecall', 'Phone Call'), ('task', 'Task'), ('appointment', 'Appointment'), ('meeting', 'Meeting'), ('note', 'Note')], db_column='activitytypecode', max_length=20),
        ),
    ]
