# Generated by Django 6.0.2 on 2026-02-20 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_activitytypecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='inreplyto',
            field=models.CharField(blank=True, db_column='inreplyto', help_text='In-Reply-To header referencing parent messageid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='matchconfidence',
            field=models.IntegerField(blank=True, db_column='matchconfidence', help_text='Auto-match confidence score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='email',
            name='matchmethod',
            field=models.CharField(blank=True, choices=[('email_address', 'Email Address'), ('tracking_token', 'Tracking Token'), ('thread_correlation', 'Thread Correlation'), ('manual', 'Manual')], db_column='matchmethod', help_text='Method used for matching: email_address, tracking_token, thread_correlation, manual', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='messageid',
            field=models.CharField(blank=True, db_column='messageid', db_index=True, help_text='RFC 5322 Message-ID header for thread correlation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='trackingtokenid',
            field=models.CharField(blank=True, db_column='trackingtokenid', db_index=True, help_text='CRM tracking token extracted from subject [CRM:OPP-abc12345]', max_length=50, null=True),
        ),
    ]
