# Generated by Django 5.0.1 on 2026-04-18 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_email_matching_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activitypoi_regardi_c388aa_idx',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['regardingobjectid', 'regardingobjectidtype', '-createdon'], name='idx_activity_reg_timeline'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-createdon'], name='idx_activity_created_desc'),
        ),
    ]
