# Generated by Django 5.0.1 on 2025-11-30 00:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('opportunities', '0002_opportunity_accountid_opportunity_contactid_and_more'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('invoiceid', models.UUIDField(db_column='invoiceid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='Invoice name/title', max_length=300)),
                ('invoicenumber', models.CharField(db_column='invoicenumber', help_text='Auto-generated invoice number (e.g., INV-2024-001)', max_length=100, unique=True)),
                ('totalamount', models.DecimalField(db_column='totalamount', decimal_places=2, default=Decimal('0.00'), help_text='Total amount (calculated from line items)', max_digits=19)),
                ('totaldiscountamount', models.DecimalField(db_column='totaldiscountamount', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totaltax', models.DecimalField(db_column='totaltax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('totallineitemamount', models.DecimalField(db_column='totallineitemamount', decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items before discounts/taxes', max_digits=19)),
                ('totalamountless', models.DecimalField(db_column='totalamountless', decimal_places=2, default=Decimal('0.00'), help_text='Total amount excluding freight and tax', max_digits=19)),
                ('totalpaid', models.DecimalField(db_column='totalpaid', decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far', max_digits=19)),
                ('totalamountdue', models.DecimalField(db_column='totalamountdue', decimal_places=2, default=Decimal('0.00'), help_text='Amount still owed (totalamount - totalpaid)', max_digits=19)),
                ('datedelivered', models.DateField(blank=True, db_column='datedelivered', help_text='Date products/services were delivered', null=True)),
                ('duedate', models.DateField(blank=True, db_column='duedate', help_text='Payment due date', null=True)),
                ('paidon', models.DateField(blank=True, db_column='paidon', help_text='Date invoice was fully paid', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Paid'), (2, 'Canceled')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'New'), (2, 'Partial'), (3, 'Complete'), (4, 'Canceled')], db_column='statuscode', default=1)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.account')),
                ('contactid', models.ForeignKey(blank=True, db_column='contactid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('opportunityid', models.ForeignKey(blank=True, db_column='opportunityid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='opportunities.opportunity')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_invoices', to=settings.AUTH_USER_MODEL)),
                ('salesorderid', models.ForeignKey(blank=True, db_column='salesorderid', help_text='Order this invoice is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('invoicedetailid', models.UUIDField(db_column='invoicedetailid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productname', help_text='Product or service name', max_length=100)),
                ('productdescription', models.TextField(blank=True, db_column='productdescription', null=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('priceperunit', models.DecimalField(db_column='priceperunit', decimal_places=2, help_text='Unit price', max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('manualdiscountamount', models.DecimalField(db_column='manualdiscountamount', decimal_places=2, default=Decimal('0.00'), help_text='Discount amount for this line', max_digits=19)),
                ('tax', models.DecimalField(db_column='tax', decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('baseamount', models.DecimalField(db_column='baseamount', decimal_places=2, help_text='quantity * priceperunit (auto-calculated)', max_digits=19)),
                ('extendedamount', models.DecimalField(db_column='extendedamount', decimal_places=2, help_text='baseamount - manualdiscountamount + tax (auto-calculated)', max_digits=19)),
                ('sequencenumber', models.IntegerField(db_column='sequencenumber', default=1)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('invoiceid', models.ForeignKey(db_column='invoiceid', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'verbose_name_plural': 'Invoice Details',
                'db_table': 'invoicedetail',
                'ordering': ['invoiceid', 'sequencenumber'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['statecode', 'ownerid'], name='invoice_stateco_45f9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['salesorderid'], name='invoice_salesor_370ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['accountid'], name='invoice_account_f84074_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoicenumber'], name='invoice_invoice_5f40ca_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['duedate'], name='invoice_duedate_a286de_idx'),
        ),
    ]
