# Generated by Django 6.0.2 on 2026-03-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='imputationcodeid',
            field=models.ForeignKey(blank=True, db_column='imputationcodeid', help_text='Imputation code for cost classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='budgets.imputationcode'),
        ),
    ]
