# Generated by Django 5.0.1 on 2026-04-23 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('projects', '0004_alter_projectsupplier_rfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBillingRule',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('ruleid', models.UUIDField(db_column='ruleid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(db_column='sequence')),
                ('percent', models.DecimalField(db_column='percent', decimal_places=4, max_digits=5)),
                ('lagperiods', models.IntegerField(db_column='lagperiods')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(db_column='projectid', on_delete=django.db.models.deletion.CASCADE, related_name='billing_rules', to='projects.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Billing Rule',
                'verbose_name_plural': 'Project Billing Rules',
                'db_table': 'projectbillingrule',
                'ordering': ['projectid', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectbillingrule',
            constraint=models.UniqueConstraint(fields=('projectid', 'sequence'), name='unique_billing_rule_seq'),
        ),
    ]
