# Generated by Django 5.0.1 on 2025-11-28 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon', help_text='Timestamp when this record was created')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon', help_text='Timestamp when this record was last modified')),
                ('opportunityid', models.UUIDField(db_column='opportunityid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=300)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('customername', models.CharField(blank=True, db_column='customername', help_text='Customer name (will be replaced with Account/Contact FK in Phase 7)', max_length=160, null=True)),
                ('estimatedrevenue', models.DecimalField(blank=True, db_column='estimatedrevenue', decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Est. Revenue')),
                ('actualrevenue', models.DecimalField(blank=True, db_column='actualrevenue', decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Revenue')),
                ('estimatedclosedate', models.DateField(blank=True, db_column='estimatedclosedate', null=True, verbose_name='Est. Close Date')),
                ('actualclosedate', models.DateField(blank=True, db_column='actualclosedate', null=True, verbose_name='Actual Close Date')),
                ('statecode', models.IntegerField(choices=[(0, 'Open'), (1, 'Won'), (2, 'Lost')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(choices=[(1, 'In Progress'), (2, 'On Hold'), (3, 'Won'), (4, 'Canceled'), (5, 'Out-Sold')], db_column='statuscode', default=1)),
                ('salesstage', models.IntegerField(choices=[(0, 'Qualify'), (1, 'Develop'), (2, 'Propose'), (3, 'Close')], db_column='salesstage', default=0, verbose_name='Sales Stage')),
                ('probability', models.IntegerField(db_column='closeprobability', default=0, help_text='Probability of closing (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probability (%)')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('originatingleadid', models.ForeignKey(blank=True, db_column='originatingleadid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to='leads.lead', verbose_name='Originating Lead')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunity',
                'ordering': ['-createdon'],
                'indexes': [models.Index(fields=['statecode', 'ownerid'], name='opportunity_stateco_2a6e57_idx'), models.Index(fields=['statuscode'], name='opportunity_statusc_599e19_idx'), models.Index(fields=['salesstage'], name='opportunity_salesst_5b9517_idx'), models.Index(fields=['ownerid', 'statecode'], name='opportunity_ownerid_c90bdd_idx'), models.Index(fields=['estimatedclosedate'], name='opportunity_estimat_c58bf8_idx'), models.Index(fields=['createdon'], name='opportunity_created_a85f97_idx')],
            },
        ),
    ]
