# Generated by Django 5.0.1 on 2025-11-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='accountid',
            field=models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='accounts.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contactid',
            field=models.ForeignKey(blank=True, db_column='contactid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='contacts.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customername',
            field=models.CharField(blank=True, db_column='customername', help_text='Legacy customer name field', max_length=160, null=True),
        ),
    ]
