# Generated by Django 5.0.1 on 2025-12-16 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('pricelevelid', models.UUIDField(db_column='pricelevelid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('begindate', models.DateField(blank=True, db_column='begindate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='enddate', null=True)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'db_table': 'pricelevel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.UUIDField(db_column='productid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statecode', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_column='statecode', default=0)),
                ('statuscode', models.IntegerField(blank=True, db_column='statuscode', null=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('productnumber', models.CharField(blank=True, db_column='productnumber', help_text='SKU or product number', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('productstructure', models.IntegerField(blank=True, choices=[(1, 'Product'), (2, 'Product Family'), (3, 'Bundle')], db_column='productstructure', default=1, null=True)),
                ('producttypecode', models.IntegerField(blank=True, choices=[(1, 'Sales Inventory'), (2, 'Miscellaneous Charges')], db_column='producttypecode', default=1, null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=4, help_text='Default selling price', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('standardcost', models.DecimalField(blank=True, db_column='standardcost', decimal_places=4, help_text='Standard cost of the product', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currentcost', models.DecimalField(blank=True, db_column='currentcost', decimal_places=4, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stockvolume', models.DecimalField(blank=True, db_column='stockvolume', decimal_places=4, max_digits=19, null=True)),
                ('stockweight', models.DecimalField(blank=True, db_column='stockweight', decimal_places=4, max_digits=19, null=True)),
                ('quantityonhand', models.DecimalField(blank=True, db_column='quantityonhand', decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantityallocated', models.DecimalField(blank=True, db_column='quantityallocated', decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vendorid', models.CharField(blank=True, db_column='vendorid', max_length=255, null=True)),
                ('vendorpartnumber', models.CharField(blank=True, db_column='vendorpartnumber', max_length=100, null=True)),
                ('vendorname', models.CharField(blank=True, db_column='vendorname', max_length=255, null=True)),
                ('size', models.CharField(blank=True, db_column='size', max_length=100, null=True)),
                ('color', models.CharField(blank=True, db_column='color', max_length=100, null=True)),
                ('style', models.CharField(blank=True, db_column='style', max_length=100, null=True)),
                ('suppliername', models.CharField(blank=True, db_column='suppliername', max_length=255, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(blank=True, db_column='modifiedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_modified', to=settings.AUTH_USER_MODEL)),
                ('parentproductid', models.ForeignKey(blank=True, db_column='parentproductid', help_text='Parent product for bundles/families', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('productpricelevelid', models.UUIDField(db_column='productpricelevelid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=4, help_text='Price for this product in this price list', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='createdon')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='modifiedon')),
                ('pricelevelid', models.ForeignKey(db_column='pricelevelid', on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='products.pricelist')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Price List Item',
                'verbose_name_plural': 'Price List Items',
                'db_table': 'productpricelevel',
                'ordering': ['pricelevelid', 'productid'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['statecode'], name='product_stateco_00d6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['productnumber'], name='product_product_663590_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['pricelevelid'], name='productpric_pricele_edc901_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['productid'], name='productpric_product_1921aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('pricelevelid', 'productid')},
        ),
    ]
